---
title: "Replicating Goodman and Wright (2015)"
subtitle: "CIVIX@Australia, New Zealand, Turkey, Argentina, and South Korea"
author: "Yuan-Ning Chu"
aus.date: "10/20/2019"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(plm) # fixed effect
library(stargazer)
```

```{r dat, echo=FALSE, warning=FALSE, message=FALSE}
aus.dat = readxl::read_xlsx("F00007577-WV6_data_Australia_2012_Excel_v20180912.xlsx") # country code 36
nz.dat = readxl::read_xlsx("F00007608-WV6_Data_New_Zealand_2011_Excel_v20180912.xlsx") # country code 554
tk.dat = readxl::read_xlsx("F00007629-WV6_Data_Turkey_2012_Excel_v20180912.xlsx") # country code 792
at.dat = readxl::read_xlsx("F00007575-WV6_Data_Argentina_2013_Excel_v20180912.xlsx") # country code 32
sk.dat = readxl::read_xlsx("F00007621-WV6_Data_South_Korea_2010_Excel_v20180912.xlsx") # country code 410

# ethnic group
aus.dat$ethnic = ifelse(aus.dat$`V254: Ethnic group` == 101, 0, 1) # 0 as Australian/English speaking, 1 as others
nz.dat$ethnic = ifelse(nz.dat$`V254: Ethnic group` == 554006 | nz.dat$`V254: Ethnic group` == 554003, 0, 1) # 554006 as NZ, 554003 as European, 0 as majority and 1 as others
# question not asked in the other three countries; assume all majority
tk.dat$ethnic = 0
at.dat$ethnic = 0
sk.dat$ethnic = 0

dat = rbind(aus.dat, nz.dat, tk.dat, at.dat, sk.dat)
```
## Descriptive statistics

```{r, echo=FALSE, warning=FALSE, message=FALSE}
table(aus.dat$`V246: Respondent citizen`)
table(nz.dat$`V246: Respondent citizen`)
table(at.dat$`V246: Respondent citizen`)
table(sk.dat$`V246: Respondent citizen`)
table(tk.dat$`V246: Respondent citizen`)
```

```{r,echo=FALSE, warning=FALSE, message=FALSE}
table(aus.dat$`V243: Mother immigrant` == 1 | aus.dat$`V244: Father immigrant` == 1)
table(nz.dat$`V243: Mother immigrant` == 1 | nz.dat$`V244: Father immigrant` == 1)
table(at.dat$`V243: Mother immigrant` == 1 | at.dat$`V244: Father immigrant` == 1)
table(sk.dat$`V243: Mother immigrant` == 1 | sk.dat$`V244: Father immigrant` == 1)
table(tk.dat$`V243: Mother immigrant` == 1 | tk.dat$`V244: Father immigrant` == 1)
```


<!-- + only have 141 immigrants for all the five countries -->
```{r, echo=FALSE, warning=FALSE, message=FALSE}
# for country fixed effect(?)
dat$country = dat$`V2: Country Code`

# control variables
dat$age = ifelse(dat$`V242: Age` > 0, dat$`V242: Age`, NA)
# dat$ethnic = ifelse(dat$`V254: Ethnic group` == 101, 0, 1) # 0 as Australian/English speaking, 1 as others
dat$gender = dat$`V240: Sex`
dat$edu = ifelse(dat$`V248: Highest educational level attained` > 0, dat$`V248: Highest educational level attained`, NA)

# DV: interested in politics
dat$poli = ifelse(dat$`V84: Interest in politics` > 0, dat$`V84: Interest in politics`, NA)

# DV: income
dat$income = ifelse(dat$`V239: Scale of incomes` > 0, dat$`V239: Scale of incomes` , NA)

# DV: employment
dat$employment = ifelse(dat$`V229: Employment status` == 1, 1, 
                        ifelse(dat$`V229: Employment status` == 2, 0, NA)) # 1 = employed, 2 = unemployed, -1 = others

# DV: subjective financial situation
dat$financial = ifelse(dat$`V237: Family savings during past year`> 0, dat$`V237: Family savings during past year`, NA) 

# DV: general trust 1
dat$trust1 = ifelse(dat$`V24: Most people can be trusted` == 2, 0,
                    ifelse(dat$`V24: Most people can be trusted` == 1, 1, NA))

# DV: general trust 2
dat$trust2 = ifelse(dat$`V56: Do you think most people would try to take advantage of you if they got a chance, or would they try to be fair?` > 0, dat$`V56: Do you think most people would try to take advantage of you if they got a chance, or would they try to be fair?`, NA) 

### fix nz.dat --> V56 is binary in NZ!

# citizenship status
dat$citizen = ifelse(dat$`V246: Respondent citizen` != 1, 0, dat$`V246: Respondent citizen`)

# second generation immigrant
dat$sec.immi = ifelse(dat$`V243: Mother immigrant` == 1 | dat$`V244: Father immigrant` == 1, 1, 0) # self-reported parent immigrant 

# native mean (citizens)
dat.mean = dat %>% filter(citizen == 1) %>% group_by(country) %>%
  select(country,poli,income,employment,financial,trust1,trust2) %>%
  summarise(mean.poli = mean(poli, na.rm = TRUE),
            mean.income = mean(income, na.rm = TRUE),
            mean.employment = mean(employment, na.rm = TRUE),
            mean.financial = mean(financial, na.rm = TRUE),
            mean.trust1 = mean(trust1, na.rm = TRUE),
            mean.trust2 = mean(trust2, na.rm = TRUE))

dat.immi = dat %>% filter(citizen != 1)
dat.1 = dat.immi %>% left_join(dat.mean, by='country')

dat.sec.immi = filter(dat, sec.immi == 1)
dat.2 = dat.sec.immi %>% left_join(dat.mean, by='country')

# dat = merge(dat.mean, dat.immi, by = "country")
# dat.citizen = filter(dat, citizen == 1)
# dat.immi = filter(dat, citizen != 1)

# table(dat$citizen) # 0 as immigrants

```
<!-- + If we include second generation immigrants, the sample size increases to 1,085.  -->
```{r, echo=FALSE, include = FALSE, warning=FALSE, message=FALSE}
# table(dat$sec.immi) # 1 as sec. gen. immigrants
```


```{r, echo=FALSE, include = FALSE, warning=FALSE, message=FALSE, eval=FALSE}
# fit.citizen = lm(poli ~ age + ethnic + gender + edu, aus.data = aus.dat.citizen)
# summary(fit.citizen)

# absolute level
fit.immi = lm(poli ~ age + ethnic + gender + edu, data = dat.1)
summary(fit.immi)

# gap w/ native mean
dat.immi$poli.gap = dat.immi$poli - dat.immi$mean.poli

fit.immi.gap = lm(poli.gap ~ age + ethnic + gender + edu, data = dat.immi)
summary(fit.immi.gap)

# 2nd generation immigrants
fit.immi.2 = lm(poli ~ age + ethnic + gender + edu, data = dat.sec.immi)
summary(fit.immi.2)
dat.sec.immi$poli.gap = dat.sec.immi$poli - dat.sec.immi$mean.poli
# gap w/ native mean
fit.immi.2.gap = lm(poli.gap ~ age + ethnic + gender + edu, data = dat.sec.immi)
summary(fit.immi.2.gap)
```

```{r, echo=FALSE, message=FALSE, warning=FALSE}
h.civix = dat.1 %>% filter(country == 36 | country == 554)
l.civix = dat.1 %>% filter(country == 792 | country == 32 | country == 410)

h.civix.sec = dat.2 %>% filter(country == 36 | country == 554)
l.civix.sec = dat.2 %>% filter(country == 792 | country == 32 | country == 410)

# gap w/ citizen
h.civix = h.civix %>% mutate(
  poli.gap = poli - mean.poli, 
  income.gap = income - mean.income,
  employment.gap = employment - mean.employment,
  finan.gap = financial - mean.financial, 
  trust1.gap = trust1 - mean.trust1,
  trust2.gap = trust2 - mean.trust2
  )

l.civix = l.civix %>% mutate(
  poli.gap = poli - mean.poli, 
  income.gap = income - mean.income,
  employment.gap = employment - mean.employment,
  finan.gap = financial - mean.financial, 
  trust1.gap = trust1 - mean.trust1,
  trust2.gap = trust2 - mean.trust2
  )

h.civix.sec = h.civix.sec %>% mutate(
  poli.gap = poli - mean.poli, 
  income.gap = income - mean.income,
  employment.gap = employment - mean.employment,
  finan.gap = financial - mean.financial, 
  trust1.gap = trust1 - mean.trust1,
  trust2.gap = trust2 - mean.trust2
  )

l.civix.sec = l.civix.sec %>% mutate(
  poli.gap = poli - mean.poli, 
  income.gap = income - mean.income,
  employment.gap = employment - mean.employment,
  finan.gap = financial - mean.financial, 
  trust1.gap = trust1 - mean.trust1,
  trust2.gap = trust2 - mean.trust2
  )
# aus.dat = dat %>% filter(country == 36)
# nz.dat = dat %>% filter(country == 554)
# tk.dat = dat %>% filter(country == 792)
# at.dat = dat %>% filter(country == 32)
# sk.dat = dat %>% filter(country == 410)

# aus.dat.immi = dat %>% filter(country == 36, citizen == 0)
# nz.dat.immi = dat %>% filter(country == 554, citizen == 0)
# tk.dat.immi = dat %>% filter(country == 792, citizen == 0)
# at.dat.immi = dat %>% filter(country == 32, citizen == 0)
# sk.dat.immi = dat %>% filter(country == 410, citizen == 0)
```

```{r, echo=FALSE, message=FALSE, warning=FALSE}
poli.h.1 = lm(poli ~ age + ethnic + gender + edu, data = h.civix) # absolute level
poli.h.2 = lm(poli.gap ~ age + ethnic + gender + edu, data = h.civix) # gap
poli.h.3 = lm(poli ~ age + ethnic + gender + edu, data = h.civix.sec) # absolute level
poli.h.4 = lm(poli.gap ~ age + ethnic + gender + edu, data = h.civix.sec) # gap

poli.l.1 = lm(poli ~ age + gender + edu, data = l.civix) # absolute level
poli.l.2 = lm(poli.gap ~ age + gender + edu, data = l.civix) # absolute level
poli.l.3 = lm(poli ~ age +  gender + edu, data = l.civix.sec) # absolute level
poli.l.4 = lm(poli.gap ~ age +  gender + edu, data = l.civix.sec) # absolute level
```

```{r, echo=FALSE, message=FALSE, warning=FALSE, fig.cap='Political interest by CIVIX', fig.height=3}
absolute.h = as.vector(c(poli.h.1$coefficients[1],confint(poli.h.1)[1,]))
absolute.l = as.vector(c(poli.l.1$coefficients[1],confint(poli.l.1)[1,]))

# sec gen
absolute.h.sec = as.vector(c(poli.h.3$coefficients[1],confint(poli.h.3)[1,]))
absolute.l.sec = as.vector(c(poli.l.3$coefficients[1],confint(poli.l.3)[1,]))

gap.h = as.vector(c(poli.h.2$coefficients[1],confint(poli.h.2)[1,]))
gap.l = as.vector(c(poli.l.2$coefficients[1],confint(poli.l.2)[1,]))

# sec gen
gap.h.sec = as.vector(c(poli.h.4$coefficients[1],confint(poli.h.4)[1,]))
gap.l.sec = as.vector(c(poli.l.4$coefficients[1],confint(poli.l.4)[1,]))


poli.1 = as.data.frame(rbind(absolute.h, absolute.l, gap.h, gap.l))
colnames(poli.1) = c("intercept", "min", "max")
poli.1 = poli.1 %>% mutate(var = c('High CIVIX: Absolute Level', 'Low CIVIX: Absolute Level','High CIVIX: Gap w/Natives','Low CIVIX: Gap w/Natives'))
poli.1$var = factor(poli.1$var, as.character(poli.1$var))

ggplot(poli.1,aes(y=var)) + 
  geom_point(aes(x = intercept)) + 
  geom_errorbarh(aes(xmin = min, xmax = max)) + 
  coord_cartesian(xlim = c(-5, 5)) + 
  geom_vline(xintercept = 0, linetype = "dashed") +
  ylab("")

```


```{r, echo=FALSE, message=FALSE, warning=FALSE, fig.cap='Political interest among 2nd generation by CIVIX', fig.height=3}

poli.2 = as.data.frame(rbind(absolute.h.sec, absolute.l.sec, gap.h.sec, gap.l.sec))
colnames(poli.2) = c("intercept", "min", "max")
poli.2 = poli.2 %>% mutate(var = c('High CIVIX: Absolute Level', 'Low CIVIX: Absolute Level','High CIVIX: Gap w/Natives','Low CIVIX: Gap w/Natives'))
poli.2$var = factor(poli.2$var, as.character(poli.2$var))

ggplot(poli.2,aes(y=var)) + 
  geom_point(aes(x = intercept)) + 
  geom_errorbarh(aes(xmin = min, xmax = max)) + 
  coord_cartesian(xlim = c(-5, 5)) + 
  geom_vline(xintercept = 0, linetype = "dashed") +
  ylab("")


```


```{r, echo=FALSE, message=FALSE, warning=FALSE}
trust1.h.1 = lm(trust1 ~ age + ethnic + gender + edu, data = h.civix) # absolute level
trust1.h.2 = lm(trust1.gap ~ age + ethnic + gender + edu, data = h.civix) # gap
trust1.h.3 = lm(trust1 ~ age + ethnic + gender + edu, data = h.civix.sec) # absolute level
trust1.h.4 = lm(trust1.gap ~ age + ethnic + gender + edu, data = h.civix.sec) # gap

trust1.l.1 = lm(trust1 ~ age + gender + edu, data = l.civix) # absolute level
trust1.l.2 = lm(trust1.gap ~ age + gender + edu, data = l.civix)# gap
trust1.l.3 = lm(trust1 ~ age + gender + edu, data = l.civix.sec) # absolute level
trust1.l.4 = lm(trust1.gap ~ age + gender + edu, data = l.civix.sec)# gap
```

```{r, echo=FALSE, message=FALSE, warning=FALSE, fig.cap='General trust by CIVIX', fig.height=3}
absolute.h = as.vector(c(trust1.h.1$coefficients[1],confint(trust1.h.1)[1,]))
absolute.l = as.vector(c(trust1.l.1$coefficients[1],confint(trust1.l.1)[1,]))

# sec gen
absolute.h.sec = as.vector(c(trust1.h.3$coefficients[1],confint(trust1.h.3)[1,]))
absolute.l.sec = as.vector(c(trust1.l.3$coefficients[1],confint(trust1.l.3)[1,]))

gap.h = as.vector(c(trust1.h.2$coefficients[1],confint(trust1.h.2)[1,]))
gap.l = as.vector(c(trust1.l.2$coefficients[1],confint(trust1.l.2)[1,]))

# sec gen
gap.h.sec = as.vector(c(trust1.h.4$coefficients[1],confint(trust1.h.4)[1,]))
gap.l.sec = as.vector(c(trust1.l.4$coefficients[1],confint(trust1.l.4)[1,]))


trust1.1 = as.data.frame(rbind(absolute.h, absolute.l, gap.h, gap.l))
colnames(trust1.1) = c("intercept", "min", "max")
trust1.1 = trust1.1 %>% mutate(var = c('High CIVIX: Absolute Level', 'Low CIVIX: Absolute Level','High CIVIX: Gap w/Natives','Low CIVIX: Gap w/Natives'))
trust1.1$var = factor(trust1.1$var, as.character(trust1.1$var))

ggplot(trust1.1,aes(y=var)) + 
  geom_point(aes(x = intercept)) + 
  geom_errorbarh(aes(xmin = min, xmax = max)) + 
  coord_cartesian(xlim = c(-1.5, 1.5)) + 
  geom_vline(xintercept = 0, linetype = "dashed") +
  ylab("")

```


```{r, echo=FALSE, message=FALSE, warning=FALSE, fig.cap='General trust among 2nd generation by CIVIX', fig.height=3}

trust1.2 = as.data.frame(rbind(absolute.h.sec, absolute.l.sec, gap.h.sec, gap.l.sec))
colnames(trust1.2) = c("intercept", "min", "max")
trust1.2 = trust1.2 %>% mutate(var = c('High CIVIX: Absolute Level', 'Low CIVIX: Absolute Level','High CIVIX: Gap w/Natives','Low CIVIX: Gap w/Natives'))
trust1.2$var = factor(trust1.2$var, as.character(trust1.2$var))

ggplot(trust1.2,aes(y=var)) + 
  geom_point(aes(x = intercept)) + 
  geom_errorbarh(aes(xmin = min, xmax = max)) + 
  coord_cartesian(xlim = c(-1.5, 1.5)) + 
  geom_vline(xintercept = 0, linetype = "dashed") +
  ylab("")


```


```{r, echo=FALSE, message=FALSE, warning=FALSE}
trust2.h.1 = lm(trust2 ~ age + ethnic + gender + edu, data = h.civix) # absolute level
trust2.h.2 = lm(trust2.gap ~ age + ethnic + gender + edu, data = h.civix) # gap
trust2.h.3 = lm(trust2 ~ age + ethnic + gender + edu, data = h.civix.sec) # absolute level
trust2.h.4 = lm(trust2.gap ~ age + ethnic + gender + edu, data = h.civix.sec) # gap

trust2.l.1 = lm(trust2 ~ age + gender + edu, data = l.civix) # absolute level
trust2.l.2 = lm(trust2.gap ~ age + gender + edu, data = l.civix)# gap
trust2.l.3 = lm(trust2 ~ age + gender + edu, data = l.civix.sec) # absolute level
trust2.l.4 = lm(trust2.gap ~ age + gender + edu, data = l.civix.sec)# gap
```

```{r, echo=FALSE, message=FALSE, warning=FALSE, fig.cap='Whether people are fair by CIVIX', fig.height=3}
absolute.h = as.vector(c(trust2.h.1$coefficients[1],confint(trust2.h.1)[1,]))
absolute.l = as.vector(c(trust2.l.1$coefficients[1],confint(trust2.l.1)[1,]))

# sec gen
absolute.h.sec = as.vector(c(trust2.h.3$coefficients[1],confint(trust2.h.3)[1,]))
absolute.l.sec = as.vector(c(trust2.l.3$coefficients[1],confint(trust2.l.3)[1,]))

gap.h = as.vector(c(trust2.h.2$coefficients[1],confint(trust2.h.2)[1,]))
gap.l = as.vector(c(trust2.l.2$coefficients[1],confint(trust2.l.2)[1,]))

# sec gen
gap.h.sec = as.vector(c(trust2.h.4$coefficients[1],confint(trust2.h.4)[1,]))
gap.l.sec = as.vector(c(trust2.l.4$coefficients[1],confint(trust2.l.4)[1,]))


trust2.1 = as.data.frame(rbind(absolute.h, absolute.l, gap.h, gap.l))
colnames(trust2.1) = c("intercept", "min", "max")
trust2.1 = trust2.1 %>% mutate(var = c('High CIVIX: Absolute Level', 'Low CIVIX: Absolute Level','High CIVIX: Gap w/Natives','Low CIVIX: Gap w/Natives'))
trust2.1$var = factor(trust2.1$var, as.character(trust2.1$var))

ggplot(trust2.1,aes(y=var)) + 
  geom_point(aes(x = intercept)) + 
  geom_errorbarh(aes(xmin = min, xmax = max)) + 
  coord_cartesian(xlim = c(-60, 60)) + 
  geom_vline(xintercept = 0, linetype = "dashed") +
  ylab("")

```


```{r, echo=FALSE, message=FALSE, warning=FALSE, fig.cap='Whether people are fair among 2nd generation by CIVIX', fig.height=3}

trust2.2 = as.data.frame(rbind(absolute.h.sec, absolute.l.sec, gap.h.sec, gap.l.sec))
colnames(trust2.2) = c("intercept", "min", "max")
trust2.2 = trust2.2 %>% mutate(var = c('High CIVIX: Absolute Level', 'Low CIVIX: Absolute Level','High CIVIX: Gap w/Natives','Low CIVIX: Gap w/Natives'))
trust2.2$var = factor(trust2.2$var, as.character(trust2.2$var))

ggplot(trust2.2,aes(y=var)) + 
  geom_point(aes(x = intercept)) + 
  geom_errorbarh(aes(xmin = min, xmax = max)) + 
  coord_cartesian(xlim = c(-60, 60)) + 
  geom_vline(xintercept = 0, linetype = "dashed") +
  ylab("")


```


```{r, echo=FALSE, message=FALSE, warning=FALSE}
income.h.1 = lm(income ~ age + ethnic + gender + edu, data = h.civix) # absolute level
income.h.2 = lm(income.gap ~ age + ethnic + gender + edu, data = h.civix) # gap
income.h.3 = lm(income ~ age + ethnic + gender + edu, data = h.civix.sec) # absolute level
income.h.4 = lm(income.gap ~ age + ethnic + gender + edu, data = h.civix.sec) # gap

income.l.1 = lm(income ~ age + gender + edu, data = l.civix) # absolute level
income.l.2 = lm(income.gap ~ age + gender + edu, data = l.civix)# gap
income.l.3 = lm(income ~ age + gender + edu, data = l.civix.sec) # absolute level
income.l.4 = lm(income.gap ~ age + gender + edu, data = l.civix.sec)# gap
```

```{r, echo=FALSE, message=FALSE, warning=FALSE, fig.cap='Household income by CIVIX', fig.height=3}
absolute.h = as.vector(c(income.h.1$coefficients[1],confint(income.h.1)[1,]))
absolute.l = as.vector(c(income.l.1$coefficients[1],confint(income.l.1)[1,]))

# sec gen
absolute.h.sec = as.vector(c(income.h.3$coefficients[1],confint(income.h.3)[1,]))
absolute.l.sec = as.vector(c(income.l.3$coefficients[1],confint(income.l.3)[1,]))

gap.h = as.vector(c(income.h.2$coefficients[1],confint(income.h.2)[1,]))
gap.l = as.vector(c(income.l.2$coefficients[1],confint(income.l.2)[1,]))

# sec gen
gap.h.sec = as.vector(c(income.h.4$coefficients[1],confint(income.h.4)[1,]))
gap.l.sec = as.vector(c(income.l.4$coefficients[1],confint(income.l.4)[1,]))


income.1 = as.data.frame(rbind(absolute.h, absolute.l, gap.h, gap.l))
colnames(income.1) = c("intercept", "min", "max")
income.1 = income.1 %>% mutate(var = c('High CIVIX: Absolute Level', 'Low CIVIX: Absolute Level','High CIVIX: Gap w/Natives','Low CIVIX: Gap w/Natives'))
income.1$var = factor(income.1$var, as.character(income.1$var))

ggplot(income.1,aes(y=var)) + 
  geom_point(aes(x = intercept)) + 
  geom_errorbarh(aes(xmin = min, xmax = max)) + 
  coord_cartesian(xlim = c(-10, 10)) + 
  geom_vline(xintercept = 0, linetype = "dashed") +
  ylab("")

```


```{r, echo=FALSE, message=FALSE, warning=FALSE, fig.cap='Household income among 2nd generation by CIVIX', fig.height=3}

income.2 = as.data.frame(rbind(absolute.h.sec, absolute.l.sec, gap.h.sec, gap.l.sec))
colnames(income.2) = c("intercept", "min", "max")
income.2 = income.2 %>% mutate(var = c('High CIVIX: Absolute Level', 'Low CIVIX: Absolute Level','High CIVIX: Gap w/Natives','Low CIVIX: Gap w/Natives'))
income.2$var = factor(income.2$var, as.character(income.2$var))

ggplot(income.2,aes(y=var)) + 
  geom_point(aes(x = intercept)) + 
  geom_errorbarh(aes(xmin = min, xmax = max)) + 
  coord_cartesian(xlim = c(-10, 10)) + 
  geom_vline(xintercept = 0, linetype = "dashed") +
  ylab("")


```


```{r, echo=FALSE, message=FALSE, warning=FALSE}
employment.h.1 = lm(employment ~ age + ethnic + gender + edu, data = h.civix) # absolute level
employment.h.2 = lm(employment.gap ~ age + ethnic + gender + edu, data = h.civix) # gap
employment.h.3 = lm(employment ~ age + ethnic + gender + edu, data = h.civix.sec) # absolute level
employment.h.4 = lm(employment.gap ~ age + ethnic + gender + edu, data = h.civix.sec) # gap

employment.l.1 = lm(employment ~ age + gender + edu, data = l.civix) # absolute level
employment.l.2 = lm(employment.gap ~ age + gender + edu, data = l.civix)# gap
employment.l.3 = lm(employment ~ age + gender + edu, data = l.civix.sec) # absolute level
employment.l.4 = lm(employment.gap ~ age + gender + edu, data = l.civix.sec)# gap
```

```{r, echo=FALSE, message=FALSE, warning=FALSE, fig.cap='Employment status by CIVIX', fig.height=3}
absolute.h = as.vector(c(employment.h.1$coefficients[1],confint(employment.h.1)[1,]))
absolute.l = as.vector(c(employment.l.1$coefficients[1],confint(employment.l.1)[1,]))

# sec gen
absolute.h.sec = as.vector(c(employment.h.3$coefficients[1],confint(employment.h.3)[1,]))
absolute.l.sec = as.vector(c(employment.l.3$coefficients[1],confint(employment.l.3)[1,]))

gap.h = as.vector(c(employment.h.2$coefficients[1],confint(employment.h.2)[1,]))
gap.l = as.vector(c(employment.l.2$coefficients[1],confint(employment.l.2)[1,]))

# sec gen
gap.h.sec = as.vector(c(employment.h.4$coefficients[1],confint(employment.h.4)[1,]))
gap.l.sec = as.vector(c(employment.l.4$coefficients[1],confint(employment.l.4)[1,]))


employment.1 = as.data.frame(rbind(absolute.h, absolute.l, gap.h, gap.l))
colnames(employment.1) = c("intercept", "min", "max")
employment.1 = employment.1 %>% mutate(var = c('High CIVIX: Absolute Level', 'Low CIVIX: Absolute Level','High CIVIX: Gap w/Natives','Low CIVIX: Gap w/Natives'))
employment.1$var = factor(employment.1$var, as.character(employment.1$var))

ggplot(employment.1,aes(y=var)) + 
  geom_point(aes(x = intercept)) + 
  geom_errorbarh(aes(xmin = min, xmax = max)) + 
  coord_cartesian(xlim = c(-5, 5)) + 
  geom_vline(xintercept = 0, linetype = "dashed") +
  ylab("")

```


```{r, echo=FALSE, message=FALSE, warning=FALSE, fig.cap='Employment status among 2nd generation by CIVIX', fig.height=3}

employment.2 = as.data.frame(rbind(absolute.h.sec, absolute.l.sec, gap.h.sec, gap.l.sec))
colnames(employment.2) = c("intercept", "min", "max")
employment.2 = employment.2 %>% mutate(var = c('High CIVIX: Absolute Level', 'Low CIVIX: Absolute Level','High CIVIX: Gap w/Natives','Low CIVIX: Gap w/Natives'))
employment.2$var = factor(employment.2$var, as.character(employment.2$var))

ggplot(employment.2,aes(y=var)) + 
  geom_point(aes(x = intercept)) + 
  geom_errorbarh(aes(xmin = min, xmax = max)) + 
  coord_cartesian(xlim = c(-5, 5)) + 
  geom_vline(xintercept = 0, linetype = "dashed") +
  ylab("")


```


```{r, echo=FALSE, message=FALSE, warning=FALSE}
financial.h.1 = lm(financial ~ age + ethnic + gender + edu, data = h.civix) # absolute level
financial.h.2 = lm(finan.gap ~ age + ethnic + gender + edu, data = h.civix) # gap
financial.h.3 = lm(financial ~ age + ethnic + gender + edu, data = h.civix.sec) # absolute level
financial.h.4 = lm(finan.gap ~ age + ethnic + gender + edu, data = h.civix.sec) # gap

financial.l.1 = lm(financial ~ age + gender + edu, data = l.civix) # absolute level
financial.l.2 = lm(finan.gap ~ age + gender + edu, data = l.civix)# gap
financial.l.3 = lm(financial ~ age + gender + edu, data = l.civix.sec) # absolute level
financial.l.4 = lm(finan.gap ~ age + gender + edu, data = l.civix.sec)# gap
```

```{r, echo=FALSE, message=FALSE, warning=FALSE, fig.cap='Financial situation by CIVIX', fig.height=3}
absolute.h = as.vector(c(financial.h.1$coefficients[1],confint(financial.h.1)[1,]))
absolute.l = as.vector(c(financial.l.1$coefficients[1],confint(financial.l.1)[1,]))

# sec gen
absolute.h.sec = as.vector(c(financial.h.3$coefficients[1],confint(financial.h.3)[1,]))
absolute.l.sec = as.vector(c(financial.l.3$coefficients[1],confint(financial.l.3)[1,]))

gap.h = as.vector(c(financial.h.2$coefficients[1],confint(financial.h.2)[1,]))
gap.l = as.vector(c(financial.l.2$coefficients[1],confint(financial.l.2)[1,]))

# sec gen
gap.h.sec = as.vector(c(financial.h.4$coefficients[1],confint(financial.h.4)[1,]))
gap.l.sec = as.vector(c(financial.l.4$coefficients[1],confint(financial.l.4)[1,]))


financial.1 = as.data.frame(rbind(absolute.h, absolute.l, gap.h, gap.l))
colnames(financial.1) = c("intercept", "min", "max")
financial.1 = financial.1 %>% mutate(var = c('High CIVIX: Absolute Level', 'Low CIVIX: Absolute Level','High CIVIX: Gap w/Natives','Low CIVIX: Gap w/Natives'))
financial.1$var = factor(financial.1$var, as.character(financial.1$var))

ggplot(financial.1,aes(y=var)) + 
  geom_point(aes(x = intercept)) + 
  geom_errorbarh(aes(xmin = min, xmax = max)) + 
  coord_cartesian(xlim = c(-5, 5)) + 
  geom_vline(xintercept = 0, linetype = "dashed") +
  ylab("")

```


```{r, echo=FALSE, message=FALSE, warning=FALSE, fig.cap='Financial situation among 2nd generation by CIVIX', fig.height=3}

financial.2 = as.data.frame(rbind(absolute.h.sec, absolute.l.sec, gap.h.sec, gap.l.sec))
colnames(financial.2) = c("intercept", "min", "max")
financial.2 = financial.2 %>% mutate(var = c('High CIVIX: Absolute Level', 'Low CIVIX: Absolute Level','High CIVIX: Gap w/Natives','Low CIVIX: Gap w/Natives'))
financial.2$var = factor(financial.2$var, as.character(financial.2$var))

ggplot(financial.2,aes(y=var)) + 
  geom_point(aes(x = intercept)) + 
  geom_errorbarh(aes(xmin = min, xmax = max)) + 
  coord_cartesian(xlim = c(-5, 5)) + 
  geom_vline(xintercept = 0, linetype = "dashed") +
  ylab("")


```

# Second Generation Immigrants in ESS

```{r ess, echo=FALSE, message=FALSE, warning=FALSE}
ess_2002 = haven::read_stata("ESS1e06_6.dta")
ess_2004 = haven::read_stata("ESS2e03_6.dta")
ess_2006 = haven::read_stata("ESS3e03_7.dta")
ess_2008 = haven::read_stata("ESS4e04_5.dta")
ess_2010 = haven::read_stata("ESS5e03_4.dta")
# table(ess_2002$cntry)
# table(ess_2002$essround)
```

```{r ess_yr, echo=FALSE, message=FALSE, warning=FALSE}
ess_2002 = ess_2002 %>% 
  select(essround, cntry, agea, blgetmg, ctzcntr, cntbrth, gndr, edulvla, facntr, mocntr, polintr, hincfel, uempla, ppltrst, pplfair) %>%
  plyr::rename(c("cntbrth"="birthplace","blgetmg"="ethnic", "edulvla"="edu"))
ess_2004 = ess_2004 %>% 
  select(essround, cntry, agea, blgetmg, ctzcntr, cntbrtha, gndr, edulvla, facntr, mocntr, polintr, hincfel, uempla, ppltrst, pplfair) %>%
  plyr::rename(c("cntbrtha"="birthplace","blgetmg"="ethnic", "edulvla"="edu"))
ess_2006 = ess_2006 %>% 
  select(essround, cntry, agea, blgetmg, ctzcntr, cntbrtha, gndr, edulvla, facntr, mocntr, polintr, hincfel, uempla, ppltrst, pplfair) %>%
  plyr::rename(c("cntbrtha"="birthplace","blgetmg"="ethnic", "edulvla"="edu"))
ess_2008 = ess_2008 %>% 
  select(essround, cntry, agea, blgetmg, ctzcntr, cntbrthb, gndr, edulvla, facntr, mocntr, polintr, hincfel, uempla, ppltrst, pplfair) %>%
  plyr::rename(c("cntbrthb"="birthplace","blgetmg"="ethnic", "edulvla"="edu"))
ess_2010 = ess_2010 %>% 
  select(essround, cntry, agea, blgetmg, ctzcntr, cntbrthb, gndr, edulvlb, facntr, mocntr, polintr, hincfel, uempla, ppltrst, pplfair) %>%
  plyr::rename(c("cntbrthb"="birthplace","blgetmg"="ethnic", "edulvlb"="edu"))

```

```{r ess_civix, echo=FALSE, message=FALSE, warning=FALSE}
ess_raw = rbind(ess_2002, ess_2004, ess_2006, ess_2008, ess_2010)
ess_raw$sec.immi = ifelse(ess_raw$facntr == 2 | ess_raw$mocntr == 2, 1, 0)
ess_raw$ethnic = ifelse(ess_raw$ethnic == 1, 1,
                        ifelse(ess_raw$ethnic == 2, 0, NA))
ess_raw$citizen = ifelse(ess_raw$ctzcntr == 1, 1,
                         ifelse(ess_raw$ctzcntr == 2, 0, NA))
ess_raw$birthplace = ifelse(ess_raw$birthplace %in% c(66,77,88,99,"02","03","04","06"), NA, ess_raw$birthplace)
  ess_raw = ess_raw[complete.cases(ess_raw$birthplace),]
  eu_member = c("BE", "FR", "DE", "IT", "LU", "NL", "DK", "IE", "GB", "GR", "PT", "ES","AT","SE")
  ess_raw$eubirth = ifelse(ess_raw$birthplace %in% eu_member, 1, 0)
ess_raw$female = ifelse(ess_raw$gndr == 2, 1, 
                        ifelse(ess_raw$gndr == 1, 0, NA))
ess_raw$edu = ifelse(ess_raw$edu > 5, NA, ess_raw$edu)

ess_raw$polintr = ifelse(ess_raw$polintr > 4, NA, ess_raw$polintr)
ess_raw$hincfel = ifelse(ess_raw$hincfel > 4, NA, ess_raw$hincfel)
ess_raw$ppltrst = ifelse(ess_raw$ppltrst > 10, NA, ess_raw$ppltrst)
ess_raw$pplfair = ifelse(ess_raw$pplfair > 10, NA, ess_raw$pplfair)

ess_mean = ess_raw %>% filter(citizen == 1) %>% group_by(cntry) %>%
  select(cntry,polintr, hincfel, uempla, ppltrst, pplfair) %>%
  summarise(mean.poli = mean(polintr, na.rm = TRUE),
            mean.uempla = mean(uempla, na.rm = TRUE),
            mean.hincfel = mean(hincfel, na.rm = TRUE),
            mean.ppltrst = mean(ppltrst, na.rm = TRUE),
            mean.pplfair = mean(pplfair, na.rm = TRUE))

ess_immi = ess_raw %>% filter(citizen == 0)
ess_raw = ess_immi %>% left_join(ess_mean, by='cntry')

ess_immi = ess_raw %>% filter(citizen == 0)
ess_sec.immi = ess_raw %>% filter(sec.immi == 1)

ess_h.immi = ess_immi %>% filter(cntry %in% c("DK", "NL", "DE", "AT", "FR", "GB", "GR"))
ess_l.immi = ess_immi %>% filter(cntry %in% c("IE", "SE", "BE", "PT", "ES", "FI","LU", "IT"))

ess_h.sec.immi = ess_sec.immi %>% filter(cntry %in% c("DK", "NL", "DE", "AT", "FR", "GB", "GR"))
ess_l.sec.immi = ess_sec.immi %>% filter(cntry %in% c("IE", "SE", "BE", "PT", "ES", "FI","LU", "IT"))
```

```{r ess_gap, echo=FALSE, message=FALSE, warning=FALSE}

ess_h.sec.immi = ess_h.sec.immi %>% mutate(
  poli.gap = polintr - mean.poli, 
  uempla.gap = uempla - mean.uempla,
  hincfel.gap = hincfel - mean.hincfel, 
  ppltrst.gap = ppltrst - mean.ppltrst,
  pplfair.gap = pplfair - mean.pplfair
  )

ess_l.sec.immi = ess_l.sec.immi %>% mutate(
  poli.gap = polintr - mean.poli, 
  uempla.gap = uempla - mean.uempla,
  hincfel.gap = hincfel - mean.hincfel, 
  ppltrst.gap = ppltrst - mean.ppltrst,
  pplfair.gap = pplfair - mean.pplfair
  )

```

```{r, echo=FALSE, message=FALSE, warning=FALSE}
polintr.h.1 = plm(polintr ~ agea + ethnic + female + edu + eubirth, data = ess_h.sec.immi, index = "essround", model = "within") # absolute level
polintr.h.2 = plm(poli.gap ~ agea + ethnic + female + edu + eubirth, data = ess_h.sec.immi, index = "essround", model = "within") # gap
polintr.l.1 = plm(polintr ~ agea + ethnic + female + edu + eubirth, data = ess_l.sec.immi, index = "essround", model = "within") # absolute level
polintr.l.2 = plm(poli.gap ~ agea + ethnic + female + edu + eubirth, data = ess_l.sec.immi, index = "essround", model = "within") # gap

absolute.h = as.vector(c(polintr.h.1$coefficients[1],confint(polintr.h.1)[1,]))
absolute.l = as.vector(c(polintr.l.1$coefficients[1],confint(polintr.l.1)[1,]))

gap.h = as.vector(c(polintr.h.2$coefficients[1],confint(polintr.h.2)[1,]))
gap.l = as.vector(c(polintr.l.2$coefficients[1],confint(polintr.l.2)[1,]))
```



```{r, echo=FALSE, message=FALSE, warning=FALSE, fig.cap='Political interests among 2nd generation by CIVIX in EU-15', fig.height=3}

polintr.1 = as.data.frame(rbind(absolute.h, absolute.l, gap.h, gap.l))
colnames(polintr.1) = c("intercept", "min", "max")
polintr.1 = polintr.1 %>% mutate(var = c('High CIVIX: Absolute Level', 'Low CIVIX: Absolute Level','High CIVIX: Gap w/Natives','Low CIVIX: Gap w/Natives'))
polintr.1$var = factor(polintr.1$var, as.character(polintr.1$var))

ggplot(polintr.1,aes(y=var)) + 
  geom_point(aes(x = intercept)) + 
  geom_errorbarh(aes(xmin = min, xmax = max)) + 
  coord_cartesian(xlim = c(-10, 10)) + 
  geom_vline(xintercept = 0, linetype = "dashed") +
  ylab("")


```

```{r, echo=FALSE, message=FALSE, warning=FALSE}
hincfel.h.1 = lm(hincfel ~ agea + ethnic + female + edu + birthplace, data = ess_h.sec.immi) # absolute level
hincfel.h.2 = lm(hincfel.gap ~ agea + ethnic + female + edu + birthplace, data = ess_h.sec.immi) # gap
hincfel.l.1 = lm(hincfel ~ agea + ethnic + female + edu + birthplace, data = ess_l.sec.immi) # absolute level
hincfel.l.2 = lm(hincfel.gap ~ agea + ethnic + female + edu + birthplace, data = ess_l.sec.immi) # gap

absolute.h = as.vector(c(hincfel.h.1$coefficients[1],confint(hincfel.h.1)[1,]))
absolute.l = as.vector(c(hincfel.l.1$coefficients[1],confint(hincfel.l.1)[1,]))

gap.h = as.vector(c(hincfel.h.2$coefficients[1],confint(hincfel.h.2)[1,]))
gap.l = as.vector(c(hincfel.l.2$coefficients[1],confint(hincfel.l.2)[1,]))
```



```{r, echo=FALSE, message=FALSE, warning=FALSE, fig.cap='Financial situation among 2nd generation by CIVIX in EU-15', fig.height=3}

hincfel.1 = as.data.frame(rbind(absolute.h, absolute.l, gap.h, gap.l))
colnames(hincfel.1) = c("intercept", "min", "max")
hincfel.1 = hincfel.1 %>% mutate(var = c('High CIVIX: Absolute Level', 'Low CIVIX: Absolute Level','High CIVIX: Gap w/Natives','Low CIVIX: Gap w/Natives'))
hincfel.1$var = factor(hincfel.1$var, as.character(hincfel.1$var))

ggplot(hincfel.1,aes(y=var)) + 
  geom_point(aes(x = intercept)) + 
  geom_errorbarh(aes(xmin = min, xmax = max)) + 
  coord_cartesian(xlim = c(-10, 10)) + 
  geom_vline(xintercept = 0, linetype = "dashed") +
  ylab("")


```

```{r, echo=FALSE, message=FALSE, warning=FALSE}
ppltrst.h.1 = lm(ppltrst ~ agea + ethnic + female + edu + birthplace, data = ess_h.sec.immi) # absolute level
ppltrst.h.2 = lm(ppltrst.gap ~ agea + ethnic + female + edu + birthplace, data = ess_h.sec.immi) # gap
ppltrst.l.1 = lm(ppltrst ~ agea + ethnic + female + edu + birthplace, data = ess_l.sec.immi) # absolute level
ppltrst.l.2 = lm(ppltrst.gap ~ agea + ethnic + female + edu + birthplace, data = ess_l.sec.immi) # gap

absolute.h = as.vector(c(ppltrst.h.1$coefficients[1],confint(ppltrst.h.1)[1,]))
absolute.l = as.vector(c(ppltrst.l.1$coefficients[1],confint(ppltrst.l.1)[1,]))

gap.h = as.vector(c(ppltrst.h.2$coefficients[1],confint(ppltrst.h.2)[1,]))
gap.l = as.vector(c(ppltrst.l.2$coefficients[1],confint(ppltrst.l.2)[1,]))
```

```{r, echo=FALSE, message=FALSE, warning=FALSE, fig.cap='General trust among 2nd generation by CIVIX in EU-15', fig.height=3}

ppltrst.1 = as.data.frame(rbind(absolute.h, absolute.l, gap.h, gap.l))
colnames(ppltrst.1) = c("intercept", "min", "max")
ppltrst.1 = ppltrst.1 %>% mutate(var = c('High CIVIX: Absolute Level', 'Low CIVIX: Absolute Level','High CIVIX: Gap w/Natives','Low CIVIX: Gap w/Natives'))
ppltrst.1$var = factor(ppltrst.1$var, as.character(ppltrst.1$var))

ggplot(ppltrst.1,aes(y=var)) + 
  geom_point(aes(x = intercept)) + 
  geom_errorbarh(aes(xmin = min, xmax = max)) + 
  coord_cartesian(xlim = c(-10, 10)) + 
  geom_vline(xintercept = 0, linetype = "dashed") +
  ylab("")


```

```{r, echo=FALSE, message=FALSE, warning=FALSE}
pplfair.h.1 = lm(pplfair ~ agea + ethnic + female + edu + birthplace, data = ess_h.sec.immi) # absolute level
pplfair.h.2 = lm(pplfair.gap ~ agea + ethnic + female + edu + birthplace, data = ess_h.sec.immi) # gap
pplfair.l.1 = lm(pplfair ~ agea + ethnic + female + edu + birthplace, data = ess_l.sec.immi) # absolute level
pplfair.l.2 = lm(pplfair.gap ~ agea + ethnic + female + edu + birthplace, data = ess_l.sec.immi) # gap

absolute.h = as.vector(c(pplfair.h.1$coefficients[1],confint(pplfair.h.1)[1,]))
absolute.l = as.vector(c(pplfair.l.1$coefficients[1],confint(pplfair.l.1)[1,]))

gap.h = as.vector(c(pplfair.h.2$coefficients[1],confint(pplfair.h.2)[1,]))
gap.l = as.vector(c(pplfair.l.2$coefficients[1],confint(pplfair.l.2)[1,]))
```

```{r, echo=FALSE, message=FALSE, warning=FALSE, fig.cap='People being fair among 2nd generation by CIVIX in EU-15', fig.height=3}

pplfair.1 = as.data.frame(rbind(absolute.h, absolute.l, gap.h, gap.l))
colnames(pplfair.1) = c("intercept", "min", "max")
pplfair.1 = pplfair.1 %>% mutate(var = c('High CIVIX: Absolute Level', 'Low CIVIX: Absolute Level','High CIVIX: Gap w/Natives','Low CIVIX: Gap w/Natives'))
pplfair.1$var = factor(pplfair.1$var, as.character(pplfair.1$var))

ggplot(pplfair.1,aes(y=var)) + 
  geom_point(aes(x = intercept)) + 
  geom_errorbarh(aes(xmin = min, xmax = max)) + 
  coord_cartesian(xlim = c(-10, 10)) + 
  geom_vline(xintercept = 0, linetype = "dashed") +
  ylab("")


```