---
title: "Anti-immigrant and CIVIX"
author: "Yuan-Ning Chu"
date: "1/24/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(plm) # fixed effect
library(ggplot2)
library(interplot)
```

```{r ess, echo=FALSE, message=FALSE, warning=FALSE}
ess_2002 = haven::read_stata("ESS1e06_6.dta")
ess_2004 = haven::read_stata("ESS2e03_6.dta")
ess_2006 = haven::read_stata("ESS3e03_7.dta")
ess_2008 = haven::read_stata("ESS4e04_5.dta")
ess_2010 = haven::read_stata("ESS5e03_4.dta")
```

```{r ess_yr, echo=FALSE, message=FALSE, warning=FALSE}
ess_2002 = ess_2002 %>% 
  dplyr::select(essround, cntry, agea, blgetmg, brncntr, ctzcntr, livecntr, cntbrth, gndr, edulvla, facntr, mocntr, polintr, polcmpl, poldcs, hincfel, uempla, ppltrst, pplfair, imsmetn, imdfetn, impcntr, imbgeco, imueclt, imwbcnt, hinctnt) %>%
  plyr::rename(c("cntbrth"="birthplace","blgetmg"="ethnic", "edulvla"="edu", "brncntr"="fborn","imsmetn"="sameim", "imdfetn"="diffim", "impcntr"="poorim", "imbgeco"="ecoim", "imueclt"="cultim", "imwbcnt"="liveim"))
  ess_2002 = ess_2002 %>% mutate(hinctnt = hinctnt/12*10) # rescale to fit data from 2008 and 2010
ess_2004 = ess_2004 %>% 
  dplyr::select(essround, cntry, agea, blgetmg, brncntr, ctzcntr, livecntr, cntbrtha, gndr, edulvla, facntr, mocntr, polintr, polcmpl, poldcs, hincfel, uempla, ppltrst, pplfair,imsmetn, imdfetn, impcntr, imbgeco, imueclt, imwbcnt, hinctnt) %>%
  plyr::rename(c("cntbrtha"="birthplace","blgetmg"="ethnic", "edulvla"="edu", "brncntr"="fborn","imsmetn"="sameim", "imdfetn"="diffim", "impcntr"="poorim", "imbgeco"="ecoim", "imueclt"="cultim", "imwbcnt"="liveim"))
  ess_2004 = ess_2004 %>% mutate(hinctnt = hinctnt/12*10)
ess_2006 = ess_2006 %>% 
  dplyr::select(essround, cntry, agea, blgetmg, brncntr, ctzcntr, livecntr, cntbrtha, gndr, edulvla, facntr, mocntr, polintr, polcmpl, poldcs, hincfel, uempla, ppltrst, pplfair, imsmetn, imdfetn, impcntr, imbgeco, imueclt, imwbcnt, hinctnt) %>%
  plyr::rename(c("cntbrtha"="birthplace","blgetmg"="ethnic", "edulvla"="edu", "brncntr"="fborn","imsmetn"="sameim", "imdfetn"="diffim", "impcntr"="poorim", "imbgeco"="ecoim", "imueclt"="cultim", "imwbcnt"="liveim"))
  ess_2006 = ess_2006 %>% mutate(hinctnt = hinctnt/12*10)
ess_2008 = ess_2008 %>% 
  dplyr::select(essround, cntry, agea, blgetmg, brncntr, ctzcntr, livecntr, cntbrthb, gndr, edulvla, facntr, mocntr, polintr, polcmpl, poldcs, hincfel, uempla, ppltrst, pplfair, imsmetn, imdfetn, impcntr, imbgeco, imueclt, imwbcnt, hinctnta) %>%
  plyr::rename(c("cntbrthb"="birthplace","blgetmg"="ethnic", "edulvla"="edu", "brncntr"="fborn","imsmetn"="sameim", "imdfetn"="diffim", "impcntr"="poorim", "imbgeco"="ecoim", "imueclt"="cultim", "imwbcnt"="liveim", "hinctnta" = "hinctnt"))
ess_2010 = ess_2010 %>% 
  dplyr::select(essround, cntry, agea, blgetmg, brncntr, ctzcntr, livecnta, cntbrthb, gndr, edulvlb, facntr, mocntr, polintr, hincfel, uempla, ppltrst, pplfair, imsmetn, imdfetn, impcntr, imbgeco, imueclt, imwbcnt, hinctnta) %>%
  plyr::rename(c("cntbrthb"="birthplace","blgetmg"="ethnic", "livecnta" = "livecntr","edulvlb"="edu", "brncntr"="fborn","imsmetn"="sameim", "imdfetn"="diffim", "impcntr"="poorim", "imbgeco"="ecoim", "imueclt"="cultim", "imwbcnt"="liveim", "hinctnta" = "hinctnt"))
  ess_2010$livecntr = ess_2010$livecntr - 2010
  ess_2010$livecntr = ifelse(ess_2010$livecntr >= 1, 1,
                           ifelse(ess_2010$livecntr %in% c(-1:-5), 2,
                                  ifelse(ess_2010$livecntr %in% c(-6:-10), 3,
                                         ifelse(ess_2010$livecntr %in% c(-11:-20), 4,
                                                ifelse(ess_2010$livecntr < -20, 5, NA)))))
  ess_2010$polcmpl = NA
  ess_2010$poldcs = NA

ess_2002 = haven::zap_labels(ess_2002)
ess_2010 = haven::zap_labels(ess_2010)
```

```{r ess_civix, echo=FALSE, message=FALSE, warning=FALSE}
ess_raw = rbind(ess_2002, ess_2004, ess_2006, ess_2008, ess_2010)
ess_raw$sec.immi = ifelse(ess_raw$facntr == 2 | ess_raw$mocntr == 2, 1, 0)
ess_raw$ethnic = ifelse(ess_raw$ethnic == 1, 1,
                        ifelse(ess_raw$ethnic == 2, 0, NA))
ess_raw$citizen = ifelse(ess_raw$ctzcntr == 1, 1,
                         ifelse(ess_raw$ctzcntr == 2, 0, NA))
ess_raw$residence = ifelse(ess_raw$livecntr <= 3, 1, 0) # 1 = lived less than 10 yrs, 0 = lived more than 10 yrs
ess_raw$fborn = ifelse(ess_raw$fborn == 1, 0, 1) # now 1 as foreign born, 0 as native born
ess_raw$birthplace = ifelse(ess_raw$birthplace %in% c(66,77,88,99,"02","03","04","06"), NA, ess_raw$birthplace)
  ess_raw = ess_raw[complete.cases(ess_raw$birthplace),]
  eu_member = c("BE", "FR", "DE", "IT", "LU", "NL", "DK", "IE", "GB", "GR", "PT", "ES","AT","SE")
ess_raw$eubirth = ifelse(ess_raw$birthplace %in% eu_member, 1, 0)
ess_raw$female = ifelse(ess_raw$gndr == 2, 1, 
                        ifelse(ess_raw$gndr == 1, 0, NA))
ess_raw$edu = ifelse(ess_raw$edu > 5, NA, ess_raw$edu)

ess_raw$polintr = ifelse(ess_raw$polintr > 4, NA, ess_raw$polintr)
# table(ess_raw$polcmpl) whether politics are too complicated to understand, 5 as always, 1 as never
# table(ess_raw$poldcs) how difficult it is to make mind up about political issues, 5 as very easy, 1 as very difficult
ess_raw$poldcs = ifelse(ess_raw$poldcs == 5, 1, # now 1 as easy
                        ifelse(ess_raw$poldcs == 4, 2, 
                               ifelse(ess_raw$poldcs == 3, 3, 
                                      ifelse(ess_raw$poldcs == 2, 4, 
                                             ifelse(ess_raw$poldcs == 1, 5, ess_raw$poldcs))))) # 5 as difficult
ess_raw$hincfel = ifelse(ess_raw$hincfel > 4, NA, ess_raw$hincfel)
ess_raw$ppltrst = ifelse(ess_raw$ppltrst > 10, NA, ess_raw$ppltrst) # 0 as can't be too careful, 10 as most people can be trusted
ess_raw$pplfair = ifelse(ess_raw$pplfair > 10, NA, ess_raw$pplfair) # 0 as most people take advantage, 10 as most people are fair
ess_raw$employ = ifelse(ess_raw$uempla == 0, 1, 0) # 1 = employed, 0 = unemployed
```


```{r anti-immigrant, message=FALSE, warning=FALSE, echo=FALSE}
ess_raw <- ess_raw %>%
  group_by(cntry) %>%
  mutate(sameimavg = mean(sameim, na.rm = T))
ess_raw <- ess_raw %>%
  group_by(cntry) %>%
  mutate(diffimavg = mean(diffim, na.rm = T))
ess_raw <- ess_raw %>%
  group_by(cntry) %>%
  mutate(poorimavg = mean(poorim, na.rm = T))
ess_raw$anti1 = (ess_raw$sameimavg + ess_raw$diffimavg + ess_raw$poorimavg)/3 
ess_raw$anti3 = (ess_raw$sameimavg + ess_raw$diffimavg + ess_raw$poorimavg)/3 / 4 * 10 # rescale

ess_raw = ess_raw %>% mutate(
  anti.b = ifelse(anti1 > 2.230, 1, 0)
)

ess_raw$ecoim <- as.numeric(ess_raw$ecoim)
library(car)
# ess_raw$ecoim = recode(ess_raw$ecoim,'0=10; 1=9; 2=8; 3=7; 4=6; 5=5; 6=4; 7=3; 8=2; 9=1; 10=0')
ess_raw <- ess_raw %>%
  group_by(cntry) %>%
  mutate(ecoimavg = mean(ecoim, na.rm = T))

ess_raw$cultim <- as.numeric(ess_raw$cultim)
# library(car)
# ess_raw$cultim = recode(ess_raw$cultim,'0=10; 1=9; 2=8; 3=7; 4=6; 5=5; 6=4; 7=3; 8=2; 9=1; 10=0')
ess_raw <- ess_raw %>%
  group_by(cntry) %>%
  mutate(cultimavg = mean(cultim, na.rm = T))

ess_raw$liveim <- as.numeric(ess_raw$liveim)
# library(car)
# ess_raw$liveim = recode(ess_raw$liveim,'0=10; 1=9; 2=8; 3=7; 4=6; 5=5; 6=4; 7=3; 8=2; 9=1; 10=0')
ess_raw <- ess_raw %>%
  group_by(cntry) %>%
  mutate(liveimavg = mean(liveim, na.rm = T))
ess_raw$anti2 = (ess_raw$ecoimavg + ess_raw$cultimavg + ess_raw$liveimavg)/3
```

```{r civix, message=FALSE, warning=FALSE, echo=FALSE}
# civix.cntry = c("AT", "BE", "DK", "FI", "FR", "DE", "GR", "IE", "NL", "PT", "ES", "SE", "GB")
#   civix.sc =   as.numeric( c(5.5, 1.25, 8.25,  2.5,    5,     7, 5.25,    1, 6.25, 1.25, 2.5, 0, 5.5))
#   civix.1 = as.data.frame(t(rbind(civix.cntry, civix.sc)))
#   colnames(civix.1) = c("cntry", "civix")
#   civix.1$civix = as.numeric(civix.1$civix)
library(readxl)
civix.1 = read_xlsx("CIVIXscores.xlsx")
table(civix.1$cntry)

ess_raw = ess_raw %>% left_join(civix.1, by = 'cntry') 
ess_raw = ess_raw %>% mutate(civix.d = ifelse(civix > 2.5, 1, 0))
```

```{r mean, message=FALSE, warning=FALSE, echo=FALSE}
ess_mean = ess_raw %>% filter(citizen == 1) %>% group_by(cntry) %>% 
  dplyr::select(cntry,polintr, hincfel, employ, ppltrst, pplfair, polcmpl, poldcs, hinctnt) %>%
  summarise(mean.poli = mean(polintr, na.rm = TRUE),
            mean.employ = mean(employ, na.rm = TRUE),
            mean.hincfel = mean(hincfel, na.rm = TRUE),
            mean.ppltrst = mean(ppltrst, na.rm = TRUE),
            mean.pplfair = mean(pplfair, na.rm = TRUE),
            mean.polcmpl = mean(polcmpl, na.rm = TRUE),
            mean.poldcs = mean(poldcs, na.rm = TRUE),
            mean.hinctnt = mean(hinctnt, na.rm = TRUE))

ess_tenyr = ess_raw %>% filter(residence == 1)

ess_tenyr = ess_tenyr %>% left_join(ess_mean, by='cntry')
ess_raw = ess_raw %>% left_join(ess_mean, by='cntry')

ess_tenyr = ess_tenyr %>% mutate(
  poli.gap = polintr - mean.poli, 
  employ.gap = employ - mean.employ,
  hincfel.gap = hincfel - mean.hincfel, 
  ppltrst.gap = ppltrst - mean.ppltrst,
  pplfair.gap = pplfair - mean.pplfair, 
  polcmpl.gap = polcmpl - mean.polcmpl,
  poldcs.gap = poldcs - mean.poldcs,
  hinctnt.gap = hinctnt - mean.hinctnt
  )

ess_h.tenyr = ess_tenyr %>% filter(civix.d == 1)
ess_l.tenyr = ess_tenyr %>% filter(civix.d == 0)

ess_anti.h = ess_tenyr %>% filter(anti1 > 2.230)
ess_anti.l = ess_tenyr %>% filter(anti1 <= 2.230)

ess_hh = ess_tenyr %>% filter(civix.d == 1 & anti1 > 2.230)
ess_hl = ess_tenyr %>% filter(civix.d == 1 & anti1 <= 2.230)
ess_lh = ess_tenyr %>% filter(civix.d == 0 & anti1 > 2.230)
ess_ll = ess_tenyr %>% filter(civix.d == 0 & anti1 <= 2.230)
```

# Descriptive 

```{r descriptive, echo=FALSE, warning=FALSE, message=FALSE, fig.height=5, fig.width=8}
dat.plot = ess_tenyr %>% 
  dplyr::select(cntry, anti1, civix, civix.d, anti.b) %>% 
  distinct(cntry, .keep_all = TRUE) %>%
  na.omit(dat.plot$civix)
dat.plot = dat.plot %>% mutate(type = ifelse(civix.d == 1 & anti1 > 2.23, "High CIVIX, High Anti-immi.",
                                             ifelse(civix.d == 1 & anti1 <=2.23, "High CIVIX, Low Anti-immi.",
                                                    ifelse(civix.d == 0 & anti1 > 2.23, "Low CIVIX, High Anti-immi.", 
                                                           ifelse(civix.d == 0 & anti1 <= 2.23, "Low CIVIX, Low Anti-immi.", NA)))))

ggplot(data = dat.plot, aes(x = civix, y = anti1, label = cntry)) + 
  geom_point(aes(shape = type)) + 
  geom_hline(yintercept = 2.23, linetype = 3) + 
  geom_vline(xintercept = 2.5, linetype = 3) +
  geom_text(nudge_x = 0.5) + 
  ylab("Anti-immigrant sentiments")

# ggsave("2by2.jpeg")
  

```
```{r sample size}
ess_raw %>% filter(civix.d == 1) %>% mutate(residence = as.factor(residence)) %>% na.omit(residence) %>%
ggplot(aes(x = residence)) +
  geom_bar(binwidth = 0.5, stat = "count") + 
  stat_count(binwidth = 0.5, stat = "count", geom = "text", colour = "white", size = 3.5,
            aes(label = ..count..),position=position_stack(vjust=0.5)) +
  scale_x_discrete("Immigrants by residence (less than 10 years)", labels = c("0" = "Natives", "1" = "Immigrants")) +
  facet_wrap(~cntry, nrow = 2) +
  # xlab("Immigrants by residence (less than 10 years)") +
  ggtitle("Sample Size in Countries with High CIVIX Scores, ESS 2002 - 2010")

ggsave("high.civix.sample.jpeg")

ess_raw %>% filter(civix.d == 0) %>% mutate(residence = as.factor(residence)) %>% na.omit(residence) %>%
ggplot(aes(x = residence)) +
  geom_bar(binwidth = 0.5, stat = "count") + 
  stat_count(binwidth = 0.5, stat = "count", geom = "text", colour = "white", size = 3.5,
            aes(label = ..count..),position=position_stack(vjust=0.5)) +
  scale_x_discrete("Immigrants by residence (less than 10 years)", labels = c("0" = "Natives", "1" = "Immigrants")) +
  facet_wrap(~cntry, nrow = 2) +
  # xlab("Immigrants by residence (less than 10 years)") +
  ggtitle("Sample Size in Countries with Low CIVIX Scores, ESS 2002 - 2010")

ggsave("low.civix.sample.jpeg")
```


```{r polintr des}
  ggplot(data = ess_h.tenyr, aes(x = polintr)) + 
  geom_histogram(binwidth = 1)  + 
  stat_bin(binwidth = 1, geom = "text", colour = "white", size = 3.5,
           aes(label = ..count..),position=position_stack(vjust=0.5)) +
  facet_wrap(~cntry, nrow = 2) + 
  xlab("Political Interest") +
  ggtitle("Countries with High CIVIX Scores")

ggsave("high.civix.polintr.jpeg")

 ggplot(data = ess_l.tenyr, aes(x = polintr)) + 
  geom_histogram(binwidth = 1)  + 
  stat_bin(binwidth = 1, geom = "text", colour = "white", size = 3.5,
           aes(label = ..count..),position=position_stack(vjust=0.5)) + 
  facet_wrap(~cntry, nrow = 2)+ 
  xlab("Political Interest") +
  ggtitle("Countries with Low CIVIX Scores")
 
 ggsave("low.civix.polintr.jpeg")
```
```{r polintr des}
  ggplot(data = ess_h.tenyr, aes(x = polintr)) + 
  geom_histogram(binwidth = 1)  + 
  stat_bin(binwidth = 1, geom = "text", colour = "white", size = 3.5,
           aes(label = ..count..),position=position_stack(vjust=0.5)) +
  facet_wrap(~cntry, nrow = 2) + 
  xlab("Political Interest") +
  ggtitle("Countries with High CIVIX Scores")

ggsave("high.civix.polintr.jpeg")

 ggplot(data = ess_l.tenyr, aes(x = polintr)) + 
  geom_histogram(binwidth = 1)  + 
  stat_bin(binwidth = 1, geom = "text", colour = "white", size = 3.5,
           aes(label = ..count..),position=position_stack(vjust=0.5)) + 
  facet_wrap(~cntry, nrow = 2)+ 
  xlab("Political Interest") +
  ggtitle("Countries with Low CIVIX Scores")
 
 ggsave("low.civix.polintr.jpeg")
```

```{r, echo=FALSE}
dat.hh = with(ess_tenyr, data.frame(agea = mean(agea, na.rm = T),
                                        ethnic = mean(ethnic, na.rm = T),
                                        female = mean(female, na.rm = T),
                                        eubirth = mean(eubirth, na.rm = T),
                                        edu = mean(edu, na.rm = T),
                                        citizen = mean(citizen, na.rm = T),
                                   anti1 = 2.23:3,
                                   civix.d = 1
                                   ))
dat.hl = with(ess_hl, data.frame(agea = mean(agea, na.rm = T),
                                        ethnic = mean(ethnic, na.rm = T),
                                        female = mean(female, na.rm = T),
                                        eubirth = mean(eubirth, na.rm = T),
                                        edu = mean(edu, na.rm = T),
                                        citizen = mean(citizen, na.rm = T),
                                   anti1 = 2:2.23,
                                   civix.d = 1
                                   ))
dat.lh = with(ess_lh, data.frame(agea = mean(agea, na.rm = T),
                                        ethnic = mean(ethnic, na.rm = T),
                                        female = mean(female, na.rm = T),
                                        eubirth = mean(eubirth, na.rm = T),
                                        edu = mean(edu, na.rm = T),
                                        citizen = mean(citizen, na.rm = T),
                                   anti1 = 2.23:3,
                                   civix.d = 0
                                   ))
dat.ll = with(ess_ll, data.frame(agea = mean(agea, na.rm = T),
                                        ethnic = mean(ethnic, na.rm = T),
                                        female = mean(female, na.rm = T),
                                        eubirth = mean(eubirth, na.rm = T),
                                        edu = mean(edu, na.rm = T),
                                        citizen = mean(citizen, na.rm = T),
                                   anti1 = 2:2.23,
                                   civix.d = 0
                                   ))
# dat.anti1 = with(ess_tenyr, data.frame(agea = mean(agea, na.rm = T),
#                                         ethnic = mean(ethnic, na.rm = T),
#                                         female = mean(female, na.rm = T),
#                                         eubirth = mean(eubirth, na.rm = T),
#                                         edu = mean(edu, na.rm = T),
#                                         citizen = mean(citizen, na.rm = T),
#                                         anti1 = 1:3
# ))
```

# Two-by-two table

```{r 2-by-2, message=FALSE, warning=FALSE}
summary(ess_raw$anti1)
t1 = ess_h.tenyr %>% group_by(cntry) %>% filter(anti1 > 2.230)
table(t1$cntry) # high CIVIX high anti-immigrant sentiments
t1.5 = ess_h.tenyr %>% group_by(cntry) %>% filter(anti1 <= 2.230)
table(t1.5$cntry)
t2 = ess_l.tenyr %>% group_by(cntry) %>% filter(anti1 > 2.230)
table(t2$cntry) # low CIVIX high anti-immigrant sentiments
t3 = ess_l.tenyr %>% group_by(cntry) %>% filter(anti1 <= 2.230)
table(t3$cntry) # low CIVIX low anti-immigrant sentiments
```

# Interactions

## Political Interests

```{r polintr.gap, message=FALSE, warning=FALSE}
summary(ess_tenyr$polintr) # political interests
summary(ess_tenyr$poli.gap) # gap with native citizens
```

```{r polintr, message=FALSE, warning=FALSE, echo=FALSE}
polintr.1 = lm(polintr ~ agea + ethnic + female + edu + eubirth + citizen + civix.d*anti1 , data = ess_tenyr)
summary(polintr.1)
polintr.2 = lm(poli.gap ~ agea + ethnic + female + edu + eubirth + citizen + civix.d*anti1 , data = ess_tenyr)
summary(polintr.2)
```

```{r predict.polintr, message=FALSE, warning=FALSE, results='asis', echo=FALSE, fig.cap='Effect of CIVIX conditional on Anti-immigrant Sentiments: Interests in Politics (Abs. Level)', fig.height=3.5}

interplot(polintr.1, var1 = "civix.d", var2 = "anti1") + 
  xlab("Anti-immigrant Sentiments") + 
  ylab("Effect of CIVIX on Incorporation") + 
  ylim(-1.5,1.5) + xlim(1.8, 2.6) +
  geom_hline(yintercept = 0, linetype = 3)

ggsave("polintr1.jpeg")
```

```{r polintr gap plot, message=FALSE, warning=FALSE, fig.cap='Effect of CIVIX conditional on Anti-immigrant Sentiments: Interests in Politics (Gap w/Natives)', fig.height=3.5, echo=FALSE}

interplot(polintr.2, var1 = "civix.d", var2 = "anti1") + 
  xlab("Anti-immigrant Sentiment") + 
  ylab("Effect of CIVIX on Incorporation") + 
  ylim(-1,1.5) + xlim(1.8, 2.6) + 
  geom_hline(yintercept = 0, linetype = 3)

ggsave("polintr2.jpeg")
```

```{r, fig.width=6, fig.height=3}

library(broom)

pred.hh.1 = polintr.1 %>%
  broom::augment(newdata = dat.hh, predict = "response") %>%
  mutate(upper = .fitted + 1.96 * .se.fit,
         lower = .fitted - 1.96 * .se.fit,
         group = "hh") %>% 
  dplyr::select(.fitted, upper, lower, group)

pred.hl.1 = polintr.1 %>%
  broom::augment(newdata = dat.hl, predict = "response") %>%
  mutate(upper = .fitted + 1.96 * .se.fit,
         lower = .fitted - 1.96 * .se.fit,
         group = "hl") %>% 
  dplyr::select(.fitted, upper, lower, group)

pred.lh.1 = polintr.1 %>%
  broom::augment(newdata = dat.lh, predict = "response") %>%
  mutate(upper = .fitted + 1.96 * .se.fit,
         lower = .fitted - 1.96 * .se.fit,
         group = "lh") %>% 
  dplyr::select(.fitted, upper, lower, group)

pred.ll.1 = polintr.1 %>%
  broom::augment(newdata = dat.ll, predict = "response") %>%
  mutate(upper = .fitted + 1.96 * .se.fit,
         lower = .fitted - 1.96 * .se.fit,
         group = "ll")%>% 
  dplyr::select(.fitted, upper, lower, group)

pred.1 = rbind(pred.hh.1, pred.hl.1, pred.lh.1, pred.ll.1)
pred.1 = pred.1 %>% mutate(group = c('High CIVIX, High Anti-immi.', 'High CIVIX, Low Anti-immi.','Low CIVIX, High Anti-immi.','Low CIVIX, Low Anti-immi.'))
pred.1 = pred.1 %>% mutate(group = factor(group, levels = c('High CIVIX, High Anti-immi.','Low CIVIX, High Anti-immi.', 'High CIVIX, Low Anti-immi.','Low CIVIX, Low Anti-immi.')))


ggplot(data = pred.1) +
  geom_errorbarh(aes(y = group, xmax = upper, xmin = lower)) + 
  geom_point(aes(y = group, x = .fitted)) +
  xlim(2,3)+ 
  xlab("Predicted Value of Political Interests") +
  ylab("")
  
ggsave("pred.polintr.1.jpeg")  


```

```{r, echo=FALSE, fig.height=3, fig.width=6}

pred.hh.2 = polintr.2 %>%
  broom::augment(newdata = dat.hh, predict = "response") %>%
  mutate(upper = .fitted + 1.96 * .se.fit,
         lower = .fitted - 1.96 * .se.fit,
         group = "hh") %>% 
  dplyr::select(.fitted, upper, lower, group)

pred.hl.2 = polintr.2 %>%
  broom::augment(newdata = dat.hl, predict = "response") %>%
  mutate(upper = .fitted + 1.96 * .se.fit,
         lower = .fitted - 1.96 * .se.fit,
         group = "hl") %>% 
  dplyr::select(.fitted, upper, lower, group)

pred.lh.2 = polintr.2 %>%
  broom::augment(newdata = dat.lh, predict = "response") %>%
  mutate(upper = .fitted + 1.96 * .se.fit,
         lower = .fitted - 1.96 * .se.fit,
         group = "lh") %>% 
  dplyr::select(.fitted, upper, lower, group)

pred.ll.2 = polintr.2 %>%
  broom::augment(newdata = dat.ll, predict = "response") %>%
  mutate(upper = .fitted + 1.96 * .se.fit,
         lower = .fitted - 1.96 * .se.fit,
         group = "ll")%>% 
  dplyr::select(.fitted, upper, lower, group)

pred.2 = rbind(pred.hh.2,  pred.lh.2, pred.hl.2, pred.ll.2)
pred.2 = pred.2 %>% mutate(group = c('High CIVIX, High Anti-immi.','Low CIVIX, High Anti-immi.', 'High CIVIX, Low Anti-immi.','Low CIVIX, Low Anti-immi.'))
pred.2 = pred.2 %>% mutate(group = factor(group, levels = c('High CIVIX, High Anti-immi.','Low CIVIX, High Anti-immi.', 'High CIVIX, Low Anti-immi.','Low CIVIX, Low Anti-immi.')))

ggplot(data = pred.2) +
  geom_errorbarh(aes(y = group, xmax = upper, xmin = lower)) + 
  geom_point(aes(y = group, x = .fitted)) +
  xlim(-0.25,0.25) + 
  xlab("Predicted Value of Political Interests (gap w/natives)") +
  ylab("")+
  geom_vline(xintercept = 0, linetype = 3)
  
ggsave("pred.polintr.2.jpeg")  
```


## Politics as Complicated

```{r polcmpl.des, message=FALSE, warning=FALSE}
summary(ess_tenyr$polcmpl) # absolute level
summary(ess_tenyr$polcmpl.gap) # gap w/natives
```


```{r polcmpl, message=FALSE, warning=FALSE, echo=FALSE}
polcmpl.1 = lm(polcmpl ~ agea + ethnic + female + edu + eubirth + citizen + civix.d*anti1 , data = ess_tenyr) # absolute level
summary(polcmpl.1)
polcmpl.2 = lm(polcmpl.gap ~ agea + ethnic + female + edu + eubirth + citizen + civix.d*anti1 , data = ess_tenyr) # gap w/ natives
summary(polcmpl.2)
```

```{r polcmpl.plot.1, message=FALSE, warning=FALSE, results='asis', echo=FALSE, fig.cap='Effect of CIVIX conditional on Anti-immigrant Sentiments: Politics as Complicated (Abs. Level)', fig.height=3.5}

interplot(polcmpl.1, var1 = "civix.d", var2 = "anti1") + 
  xlab("Anti-immigrant Sentiments") + 
  ylab("Effect of CIVIX on Incorporation") + 
  ylim(-1.5,1.5) + xlim(1.8, 2.6) +
  geom_hline(yintercept = 0, linetype = 3)

ggsave("polcmpl1.jpeg")
```


```{r polcmpl.plot.2, message=FALSE, warning=FALSE, results='asis', echo=FALSE, fig.cap='Effect of CIVIX conditional on Anti-immigrant Sentiments: Politics as Complicated (Gap w/Natives)', fig.height=3.5}

interplot(polcmpl.2, var1 = "civix.d", var2 = "anti1") + 
  xlab("Anti-immigrant Sentiments") + 
  ylab("Effect of CIVIX on Incorporation") + 
  ylim(-1.5,1.5) + xlim(1.8, 2.6) +
  geom_hline(yintercept = 0, linetype = 3)

ggsave("polcmpl2.jpeg")
```



```{r, echo=FALSE, fig.height=3, fig.width=6}
pred.hh.1 = polcmpl.1 %>%
  broom::augment(newdata = dat.hh, predict = "response") %>%
  mutate(upper = .fitted + 1.96 * .se.fit,
         lower = .fitted - 1.96 * .se.fit,
         group = "hh") %>% 
  dplyr::select(.fitted, upper, lower, group)

pred.hl.1 = polcmpl.1 %>%
  broom::augment(newdata = dat.hl, predict = "response") %>%
  mutate(upper = .fitted + 1.96 * .se.fit,
         lower = .fitted - 1.96 * .se.fit,
         group = "hl") %>% 
  dplyr::select(.fitted, upper, lower, group)

pred.lh.1 = polcmpl.1 %>%
  broom::augment(newdata = dat.lh, predict = "response") %>%
  mutate(upper = .fitted + 1.96 * .se.fit,
         lower = .fitted - 1.96 * .se.fit,
         group = "lh") %>% 
  dplyr::select(.fitted, upper, lower, group)

pred.ll.1 = polcmpl.1 %>%
  broom::augment(newdata = dat.ll, predict = "response") %>%
  mutate(upper = .fitted + 1.96 * .se.fit,
         lower = .fitted - 1.96 * .se.fit,
         group = "ll")%>% 
  dplyr::select(.fitted, upper, lower, group)

pred.1 = rbind(pred.hh.1, pred.hl.1, pred.lh.1, pred.ll.1)
pred.1 = pred.1 %>% mutate(group = c('High CIVIX, High Anti-immi.', 'High CIVIX, Low Anti-immi.','Low CIVIX, High Anti-immi.','Low CIVIX, Low Anti-immi.'))
pred.1 = pred.1 %>% mutate(group = factor(group, levels = c('High CIVIX, High Anti-immi.','Low CIVIX, High Anti-immi.', 'High CIVIX, Low Anti-immi.','Low CIVIX, Low Anti-immi.')))


ggplot(data = pred.1) +
  geom_errorbarh(aes(y = group, xmax = upper, xmin = lower)) + 
  geom_point(aes(y = group, x = .fitted)) +
  xlim(2.5,3.5)+ 
  xlab("Predicted Value of Politics as Complicated") +
  ylab("")
  
ggsave("pred.polcmpl.1.jpeg")  

```

```{r, echo=FALSE, fig.height=3, fig.width=6}
pred.hh.2 = polcmpl.2 %>%
  broom::augment(newdata = dat.hh, predict = "response") %>%
  mutate(upper = .fitted + 1.96 * .se.fit,
         lower = .fitted - 1.96 * .se.fit,
         group = "hh") %>% 
  dplyr::select(.fitted, upper, lower, group)

pred.hl.2 = polcmpl.2 %>%
  broom::augment(newdata = dat.hl, predict = "response") %>%
  mutate(upper = .fitted + 1.96 * .se.fit,
         lower = .fitted - 1.96 * .se.fit,
         group = "hl") %>% 
  dplyr::select(.fitted, upper, lower, group)

pred.lh.2 = polcmpl.2 %>%
  broom::augment(newdata = dat.lh, predict = "response") %>%
  mutate(upper = .fitted + 1.96 * .se.fit,
         lower = .fitted - 1.96 * .se.fit,
         group = "lh") %>% 
  dplyr::select(.fitted, upper, lower, group)

pred.ll.2 = polcmpl.2 %>%
  broom::augment(newdata = dat.ll, predict = "response") %>%
  mutate(upper = .fitted + 1.96 * .se.fit,
         lower = .fitted - 1.96 * .se.fit,
         group = "ll")%>% 
  dplyr::select(.fitted, upper, lower, group)

pred.2 = rbind(pred.hh.2, pred.hl.2, pred.lh.2, pred.ll.2)
pred.2 = pred.2 %>% mutate(group = c('High CIVIX, High Anti-immi.', 'High CIVIX, Low Anti-immi.','Low CIVIX, High Anti-immi.','Low CIVIX, Low Anti-immi.'))
pred.1 = pred.2 %>% mutate(group = factor(group, levels = c('High CIVIX, High Anti-immi.','Low CIVIX, High Anti-immi.', 'High CIVIX, Low Anti-immi.','Low CIVIX, Low Anti-immi.')))

ggplot(data = pred.2) +
  geom_errorbarh(aes(y = group, xmax = upper, xmin = lower)) + 
  geom_point(aes(y = group, x = .fitted)) +
  xlim(-0.5,0.5)+ 
  xlab("Predicted Value of Politics as Complicated (gap w/natives") +
  ylab("")+
  geom_vline(xintercept = 0, linetype = 3)
  
ggsave("pred.polcmpl.2.jpeg")  

```


## Difficulty in making political decisions

```{r poldcs.des, message=FALSE, warning=FALSE}
summary(ess_tenyr$poldcs) # absolute level
summary(ess_tenyr$poldcs.gap)
```

```{r poldcs, message=FALSE, warning=FALSE, echo=FALSE}
poldcs.1 = lm(poldcs ~ agea + ethnic + female + edu + eubirth + citizen + civix.d*anti1 , data = ess_tenyr) # absolute level
summary(poldcs.1)
poldcs.2 = lm(poldcs.gap ~ agea + ethnic + female + edu + eubirth + citizen + civix.d*anti1 , data = ess_tenyr) # gap w/natives
summary(poldcs.2)
```

```{r poldcs.1.plot, message=FALSE, warning=FALSE, results='asis', echo=FALSE, fig.height=3.5}

interplot(poldcs.1, var1 = "civix.d", var2 = "anti1") + 
  xlab("Anti-immigrant Sentiments") + 
  ylab("Effect of CIVIX on Incorporation") + 
  ylim(-1.5,1.5) + xlim(1.8, 2.6) +
  geom_hline(yintercept = 0, linetype = 3)

ggsave("poldcs1.jpeg")
```

```{r poldcs.2.plot, message=FALSE, warning=FALSE, results='asis', echo=FALSE, fig.height=3.5}

interplot(poldcs.2, var1 = "civix.d", var2 = "anti1") + 
  xlab("Anti-immigrant Sentiments") + 
  ylab("Effect of CIVIX on Incorporation") + 
  ylim(-1.5,1.5) + xlim(1.8, 2.6) +
  geom_hline(yintercept = 0, linetype = 3)

ggsave("poldcs2.jpeg")
```

```{r, echo=FALSE, fig.height=3, fig.width=6}
pred.hh.1 = poldcs.1 %>%
  broom::augment(newdata = dat.hh, predict = "response") %>%
  mutate(upper = .fitted + 1.96 * .se.fit,
         lower = .fitted - 1.96 * .se.fit,
         group = "hh") %>% 
  dplyr::select(.fitted, upper, lower, group)

pred.hl.1 = poldcs.1 %>%
  broom::augment(newdata = dat.hl, predict = "response") %>%
  mutate(upper = .fitted + 1.96 * .se.fit,
         lower = .fitted - 1.96 * .se.fit,
         group = "hl") %>% 
  dplyr::select(.fitted, upper, lower, group)

pred.lh.1 = poldcs.1 %>%
  broom::augment(newdata = dat.lh, predict = "response") %>%
  mutate(upper = .fitted + 1.96 * .se.fit,
         lower = .fitted - 1.96 * .se.fit,
         group = "lh") %>% 
  dplyr::select(.fitted, upper, lower, group)

pred.ll.1 = poldcs.1 %>%
  broom::augment(newdata = dat.ll, predict = "response") %>%
  mutate(upper = .fitted + 1.96 * .se.fit,
         lower = .fitted - 1.96 * .se.fit,
         group = "ll")%>% 
  dplyr::select(.fitted, upper, lower, group)

pred.1 = rbind(pred.hh.1, pred.hl.1, pred.lh.1, pred.ll.1)
pred.1 = pred.1 %>% mutate(group = c('High CIVIX, High Anti-immi.', 'High CIVIX, Low Anti-immi.','Low CIVIX, High Anti-immi.','Low CIVIX, Low Anti-immi.'))
pred.1 = pred.1 %>% mutate(group = factor(group, levels = c('High CIVIX, High Anti-immi.','Low CIVIX, High Anti-immi.', 'High CIVIX, Low Anti-immi.','Low CIVIX, Low Anti-immi.')))


ggplot(data = pred.1) +
  geom_errorbarh(aes(y = group, xmax = upper, xmin = lower)) + 
  geom_point(aes(y = group, x = .fitted)) +
  xlim(2.5,3.5)+ 
  xlab("Predicted Value of Difficulty in Poli. Decisions") +
  ylab("")
  
ggsave("pred.poldcs.1.jpeg")  

```

```{r, echo=FALSE, fig.height=3, fig.width=6}
pred.hh.2 = poldcs.2 %>%
  broom::augment(newdata = dat.hh, predict = "response") %>%
  mutate(upper = .fitted + 1.96 * .se.fit,
         lower = .fitted - 1.96 * .se.fit,
         group = "hh") %>% 
  dplyr::select(.fitted, upper, lower, group)

pred.hl.2 = poldcs.2 %>%
  broom::augment(newdata = dat.hl, predict = "response") %>%
  mutate(upper = .fitted + 1.96 * .se.fit,
         lower = .fitted - 1.96 * .se.fit,
         group = "hl") %>% 
  dplyr::select(.fitted, upper, lower, group)

pred.lh.2 = poldcs.2 %>%
  broom::augment(newdata = dat.lh, predict = "response") %>%
  mutate(upper = .fitted + 1.96 * .se.fit,
         lower = .fitted - 1.96 * .se.fit,
         group = "lh") %>% 
  dplyr::select(.fitted, upper, lower, group)

pred.ll.2 = poldcs.2 %>%
  broom::augment(newdata = dat.ll, predict = "response") %>%
  mutate(upper = .fitted + 1.96 * .se.fit,
         lower = .fitted - 1.96 * .se.fit,
         group = "ll")%>% 
  dplyr::select(.fitted, upper, lower, group)

pred.2 = rbind(pred.hh.2, pred.hl.2, pred.lh.2, pred.ll.2)
pred.2 = pred.2 %>% mutate(group = c('High CIVIX, High Anti-immi.', 'High CIVIX, Low Anti-immi.','Low CIVIX, High Anti-immi.','Low CIVIX, Low Anti-immi.'))
pred.2 = pred.2 %>% mutate(group = factor(group, levels = c('High CIVIX, High Anti-immi.','Low CIVIX, High Anti-immi.', 'High CIVIX, Low Anti-immi.','Low CIVIX, Low Anti-immi.')))


ggplot(data = pred.2) +
  geom_errorbarh(aes(y = group, xmax = upper, xmin = lower)) + 
  geom_point(aes(y = group, x = .fitted)) +
  xlim(-0.5,0.5)+ 
  xlab("Predicted Value of Difficulty in Poli. Decisions") +
  ylab("")+
  geom_vline(xintercept = 0, linetype = 3)
  
ggsave("pred.poldcs.2.jpeg")  

```

## Employment status

```{r}
summary(ess_tenyr$employ)
summary(ess_tenyr$employ.gap)
```

```{r employ, message=FALSE, warning=FALSE, echo=FALSE}
employ.1 = lm(employ ~ agea + ethnic + female + edu + eubirth + citizen + civix.d*anti1, data = ess_tenyr) # absolute level
summary(employ.1)
employ.2 = lm(employ.gap ~ agea + ethnic + female + edu + eubirth + citizen + civix.d*anti1 , data = ess_tenyr) # gap w/natives
summary(employ.2)
```

```{r employ.1, message=FALSE, warning=FALSE, results='asis', echo=FALSE, fig.height=3.5}

interplot(employ.1, var1 = "civix.d", var2 = "anti1") + 
  xlab("Anti-immigrant Sentiments") + 
  ylab("Effect of CIVIX on Incorporation") + 
  ylim(-1.5,1.5) + xlim(1.8, 2.6) +
  geom_hline(yintercept = 0, linetype = 3)

ggsave("employ1.jpeg")
```

```{r employ.2, message=FALSE, warning=FALSE, results='asis', echo=FALSE, fig.height=3.5}

interplot(employ.2, var1 = "civix.d", var2 = "anti1") + 
  xlab("Anti-immigrant Sentiments") + 
  ylab("Effect of CIVIX on Incorporation") + 
  ylim(-1.5,1.5) + xlim(1.8, 2.6) +
  geom_hline(yintercept = 0, linetype = 3)

ggsave("employ2.jpeg")
```

```{r, echo=FALSE, fig.height=3, fig.width=6}
pred.hh.1 = employ.1 %>%
  broom::augment(newdata = dat.hh, predict = "response") %>%
  mutate(upper = .fitted + 1.96 * .se.fit,
         lower = .fitted - 1.96 * .se.fit,
         group = "hh") %>% 
  dplyr::select(.fitted, upper, lower, group)

pred.hl.1 = employ.1 %>%
  broom::augment(newdata = dat.hl, predict = "response") %>%
  mutate(upper = .fitted + 1.96 * .se.fit,
         lower = .fitted - 1.96 * .se.fit,
         group = "hl") %>% 
  dplyr::select(.fitted, upper, lower, group)

pred.lh.1 = employ.1 %>%
  broom::augment(newdata = dat.lh, predict = "response") %>%
  mutate(upper = .fitted + 1.96 * .se.fit,
         lower = .fitted - 1.96 * .se.fit,
         group = "lh") %>% 
  dplyr::select(.fitted, upper, lower, group)

pred.ll.1 = employ.1 %>%
  broom::augment(newdata = dat.ll, predict = "response") %>%
  mutate(upper = .fitted + 1.96 * .se.fit,
         lower = .fitted - 1.96 * .se.fit,
         group = "ll")%>% 
  dplyr::select(.fitted, upper, lower, group)

pred.1 = rbind(pred.hh.1, pred.hl.1, pred.lh.1, pred.ll.1)
pred.1 = pred.1 %>% mutate(group = c('High CIVIX, High Anti-immi.', 'High CIVIX, Low Anti-immi.','Low CIVIX, High Anti-immi.','Low CIVIX, Low Anti-immi.'))
pred.1 = pred.1 %>% mutate(group = factor(group, levels = c('High CIVIX, High Anti-immi.','Low CIVIX, High Anti-immi.', 'High CIVIX, Low Anti-immi.','Low CIVIX, Low Anti-immi.')))


ggplot(data = pred.1) +
  geom_errorbarh(aes(y = group, xmax = upper, xmin = lower)) + 
  geom_point(aes(y = group, x = .fitted)) +
  xlim(0.5,1)+ 
  xlab("Predicted Probability of Employment") +
  ylab("")
  
ggsave("pred.employ.1.jpeg")  

```

```{r, echo=FALSE, fig.height=3, fig.width=6}
pred.hh.2 = employ.2 %>%
  broom::augment(newdata = dat.hh, predict = "response") %>%
  mutate(upper = .fitted + 1.96 * .se.fit,
         lower = .fitted - 1.96 * .se.fit,
         group = "hh") %>% 
  dplyr::select(.fitted, upper, lower, group)

pred.hl.2 = employ.2 %>%
  broom::augment(newdata = dat.hl, predict = "response") %>%
  mutate(upper = .fitted + 1.96 * .se.fit,
         lower = .fitted - 1.96 * .se.fit,
         group = "hl") %>% 
  dplyr::select(.fitted, upper, lower, group)

pred.lh.2 = employ.2 %>%
  broom::augment(newdata = dat.lh, predict = "response") %>%
  mutate(upper = .fitted + 1.96 * .se.fit,
         lower = .fitted - 1.96 * .se.fit,
         group = "lh") %>% 
  dplyr::select(.fitted, upper, lower, group)

pred.ll.2 = employ.2 %>%
  broom::augment(newdata = dat.ll, predict = "response") %>%
  mutate(upper = .fitted + 1.96 * .se.fit,
         lower = .fitted - 1.96 * .se.fit,
         group = "ll")%>% 
  dplyr::select(.fitted, upper, lower, group)

pred.2 = rbind(pred.hh.2, pred.hl.2, pred.lh.2, pred.ll.2)
pred.2 = pred.2 %>% mutate(group = c('High CIVIX, High Anti-immi.', 'High CIVIX, Low Anti-immi.','Low CIVIX, High Anti-immi.','Low CIVIX, Low Anti-immi.'))
pred.2 = pred.2 %>% mutate(group = factor(group, levels = c('High CIVIX, High Anti-immi.','Low CIVIX, High Anti-immi.', 'High CIVIX, Low Anti-immi.','Low CIVIX, Low Anti-immi.')))


ggplot(data = pred.2) +
  geom_errorbarh(aes(y = group, xmax = upper, xmin = lower)) + 
  geom_point(aes(y = group, x = .fitted)) +
  xlim(-0.25,0.25)+ 
  xlab("Predicted Probability of Employment (gap w/natives)") +
  ylab("")+
  geom_vline(xintercept = 0, linetype = 3)
  
ggsave("pred.employ.2.jpeg")  

```

## People being fair

```{r}
summary(ess_tenyr$pplfair)
summary(ess_tenyr$pplfair.gap)
```

```{r pplfair, echo=FALSE}
pplfair.1 = lm(pplfair ~ agea + ethnic + female + edu + eubirth + citizen + civix.d*anti1, data = ess_tenyr) # absolute level
summary(pplfair.1)
pplfair.2 = lm(pplfair.gap ~ agea + ethnic + female + edu + eubirth + citizen + civix.d*anti1 , data = ess_tenyr) # gap w/natives
summary(pplfair.2)
```

```{r pplfair.1, message=FALSE, warning=FALSE, results='asis', echo=FALSE, fig.height=3.5}

interplot(pplfair.1, var1 = "civix.d", var2 = "anti1") + 
  xlab("Anti-immigrant Sentiments") + 
  ylab("Effect of CIVIX on Incorporation") + 
  ylim(-2.5,2.5) + xlim(1.8, 2.6) +
  geom_hline(yintercept = 0, linetype = 3)

ggsave("pplfair1.jpeg")
```

```{r pplfair.2, message=FALSE, warning=FALSE, results='asis', echo=FALSE, fig.height=3.5}

interplot(pplfair.2, var1 = "civix.d", var2 = "anti1") + 
  xlab("Anti-immigrant Sentiments") + 
  ylab("Effect of CIVIX on Incorporation") + 
  ylim(-1,1) + xlim(1.8, 2.6) +
  geom_hline(yintercept = 0, linetype = 3)

ggsave("pplfair2.jpeg")
```

```{r, echo=FALSE, fig.height=3, fig.width=6}
pred.hh.1 = pplfair.1 %>%
  broom::augment(newdata = dat.hh, predict = "response") %>%
  mutate(upper = .fitted + 1.96 * .se.fit,
         lower = .fitted - 1.96 * .se.fit,
         group = "hh") %>% 
  dplyr::select(.fitted, upper, lower, group)

pred.hl.1 = pplfair.1 %>%
  broom::augment(newdata = dat.hl, predict = "response") %>%
  mutate(upper = .fitted + 1.96 * .se.fit,
         lower = .fitted - 1.96 * .se.fit,
         group = "hl") %>% 
  dplyr::select(.fitted, upper, lower, group)

pred.lh.1 = pplfair.1 %>%
  broom::augment(newdata = dat.lh, predict = "response") %>%
  mutate(upper = .fitted + 1.96 * .se.fit,
         lower = .fitted - 1.96 * .se.fit,
         group = "lh") %>% 
  dplyr::select(.fitted, upper, lower, group)

pred.ll.1 = pplfair.1 %>%
  broom::augment(newdata = dat.ll, predict = "response") %>%
  mutate(upper = .fitted + 1.96 * .se.fit,
         lower = .fitted - 1.96 * .se.fit,
         group = "ll")%>% 
  dplyr::select(.fitted, upper, lower, group)

pred.1 = rbind(pred.hh.1, pred.hl.1, pred.lh.1, pred.ll.1)
pred.1 = pred.1 %>% mutate(group = c('High CIVIX, High Anti-immi.', 'High CIVIX, Low Anti-immi.','Low CIVIX, High Anti-immi.','Low CIVIX, Low Anti-immi.'))
pred.1 = pred.1 %>% mutate(group = factor(group, levels = c('High CIVIX, High Anti-immi.','Low CIVIX, High Anti-immi.', 'High CIVIX, Low Anti-immi.','Low CIVIX, Low Anti-immi.')))


ggplot(data = pred.1) +
  geom_errorbarh(aes(y = group, xmax = upper, xmin = lower)) + 
  geom_point(aes(y = group, x = .fitted)) +
  xlim(5,7)+ 
  xlab("Predicted Value of Considering People Being Fair") + # 0 as most people take advantage, 10 as most people are fair
  ylab("") 
  
ggsave("pred.pplfair.1.jpeg")  

```

```{r, echo=FALSE, fig.height=3, fig.width=6}
pred.hh.2 = pplfair.2 %>%
  broom::augment(newdata = dat.hh, predict = "response") %>%
  mutate(upper = .fitted + 1.96 * .se.fit,
         lower = .fitted - 1.96 * .se.fit,
         group = "hh") %>% 
  dplyr::select(.fitted, upper, lower, group)

pred.hl.2 = pplfair.2 %>%
  broom::augment(newdata = dat.hl, predict = "response") %>%
  mutate(upper = .fitted + 1.96 * .se.fit,
         lower = .fitted - 1.96 * .se.fit,
         group = "hl") %>% 
  dplyr::select(.fitted, upper, lower, group)

pred.lh.2 = pplfair.2 %>%
  broom::augment(newdata = dat.lh, predict = "response") %>%
  mutate(upper = .fitted + 1.96 * .se.fit,
         lower = .fitted - 1.96 * .se.fit,
         group = "lh") %>% 
  dplyr::select(.fitted, upper, lower, group)

pred.ll.2 = pplfair.2 %>%
  broom::augment(newdata = dat.ll, predict = "response") %>%
  mutate(upper = .fitted + 1.96 * .se.fit,
         lower = .fitted - 1.96 * .se.fit,
         group = "ll")%>% 
  dplyr::select(.fitted, upper, lower, group)

pred.2 = rbind(pred.hh.2, pred.hl.2, pred.lh.2, pred.ll.2)
pred.2 = pred.2 %>% mutate(group = c('High CIVIX, High Anti-immi.', 'High CIVIX, Low Anti-immi.','Low CIVIX, High Anti-immi.','Low CIVIX, Low Anti-immi.'))
pred.2 = pred.2 %>% mutate(group = factor(group, levels = c('High CIVIX, High Anti-immi.','Low CIVIX, High Anti-immi.', 'High CIVIX, Low Anti-immi.','Low CIVIX, Low Anti-immi.')))


ggplot(data = pred.2) +
  geom_errorbarh(aes(y = group, xmax = upper, xmin = lower)) + 
  geom_point(aes(y = group, x = .fitted)) +
  xlim(-1,1)+ 
  xlab("Predicted Value of Considering People Being Fair (gap w/natives)") +
  ylab("") +
  geom_vline(xintercept = 0, linetype = 3)
  
ggsave("pred.pplfair.2.jpeg")  

```


## General Trust

```{r}
summary(ess_tenyr$ppltrst) # 0 as can't be too careful, 10 as most people can be trusted
summary(ess_tenyr$ppltrst.gap)
```

```{r ppltrst, echo=FALSE}
ppltrst.1 = lm(ppltrst ~ agea + ethnic + female + edu + eubirth + citizen + civix.d*anti1, data = ess_tenyr) # absolute level
summary(ppltrst.1)
ppltrst.2 = lm(ppltrst.gap ~ agea + ethnic + female + edu + eubirth + citizen + civix.d*anti1 , data = ess_tenyr) # gap w/natives
summary(ppltrst.2)
```

```{r ppltrst.1, message=FALSE, warning=FALSE, results='asis', echo=FALSE, fig.height=3.5}

interplot(ppltrst.1, var1 = "civix.d", var2 = "anti1") + 
  xlab("Anti-immigrant Sentiments") + 
  ylab("Effect of CIVIX on Incorporation") + 
  ylim(-1.5,1.5) + xlim(1.8, 2.6) +
  geom_hline(yintercept = 0, linetype = 3)

ggsave("ppltrst1.jpeg")
```

```{r ppltrst.2, message=FALSE, warning=FALSE, results='asis', echo=FALSE, fig.height=3.5}

interplot(ppltrst.2, var1 = "civix.d", var2 = "anti1") + 
  xlab("Anti-immigrant Sentiments") + 
  ylab("Effect of CIVIX on Incorporation") + 
  ylim(-1,1) + xlim(1.8, 2.6) +
  geom_hline(yintercept = 0, linetype = 3)

ggsave("ppltrst2.jpeg")
```

```{r, echo=FALSE, fig.height=3, fig.width=6}
pred.hh.1 = ppltrst.1 %>%
  broom::augment(newdata = dat.hh, predict = "response") %>%
  mutate(upper = .fitted + 1.96 * .se.fit,
         lower = .fitted - 1.96 * .se.fit,
         group = "hh") %>% 
  dplyr::select(.fitted, upper, lower, group)

pred.hl.1 = ppltrst.1 %>%
  broom::augment(newdata = dat.hl, predict = "response") %>%
  mutate(upper = .fitted + 1.96 * .se.fit,
         lower = .fitted - 1.96 * .se.fit,
         group = "hl") %>% 
  dplyr::select(.fitted, upper, lower, group)

pred.lh.1 = ppltrst.1 %>%
  broom::augment(newdata = dat.lh, predict = "response") %>%
  mutate(upper = .fitted + 1.96 * .se.fit,
         lower = .fitted - 1.96 * .se.fit,
         group = "lh") %>% 
  dplyr::select(.fitted, upper, lower, group)

pred.ll.1 = ppltrst.1 %>%
  broom::augment(newdata = dat.ll, predict = "response") %>%
  mutate(upper = .fitted + 1.96 * .se.fit,
         lower = .fitted - 1.96 * .se.fit,
         group = "ll")%>% 
  dplyr::select(.fitted, upper, lower, group)

pred.1 = rbind(pred.hh.1, pred.hl.1, pred.lh.1, pred.ll.1)
pred.1 = pred.1 %>% mutate(group = c('High CIVIX, High Anti-immi.', 'High CIVIX, Low Anti-immi.','Low CIVIX, High Anti-immi.','Low CIVIX, Low Anti-immi.'))
pred.1 = pred.1 %>% mutate(group = factor(group, levels = c('High CIVIX, High Anti-immi.','Low CIVIX, High Anti-immi.', 'High CIVIX, Low Anti-immi.','Low CIVIX, Low Anti-immi.')))


ggplot(data = pred.1) +
  geom_errorbarh(aes(y = group, xmax = upper, xmin = lower)) + 
  geom_point(aes(y = group, x = .fitted)) +
  xlim(4.5,6)+ 
  xlab("Predicted Value of General Trust") +
  ylab("")
  
ggsave("pred.ppltrst.1.jpeg")  

```

```{r, echo=FALSE, fig.height=3, fig.width=6}
pred.hh.2 = ppltrst.2 %>%
  broom::augment(newdata = dat.hh, predict = "response") %>%
  mutate(upper = .fitted + 1.96 * .se.fit,
         lower = .fitted - 1.96 * .se.fit,
         group = "hh") %>% 
  dplyr::select(.fitted, upper, lower, group)

pred.hl.2 = ppltrst.2 %>%
  broom::augment(newdata = dat.hl, predict = "response") %>%
  mutate(upper = .fitted + 1.96 * .se.fit,
         lower = .fitted - 1.96 * .se.fit,
         group = "hl") %>% 
  dplyr::select(.fitted, upper, lower, group)

pred.lh.2 = ppltrst.2 %>%
  broom::augment(newdata = dat.lh, predict = "response") %>%
  mutate(upper = .fitted + 1.96 * .se.fit,
         lower = .fitted - 1.96 * .se.fit,
         group = "lh") %>% 
  dplyr::select(.fitted, upper, lower, group)

pred.ll.2 = ppltrst.2 %>%
  broom::augment(newdata = dat.ll, predict = "response") %>%
  mutate(upper = .fitted + 1.96 * .se.fit,
         lower = .fitted - 1.96 * .se.fit,
         group = "ll")%>% 
  dplyr::select(.fitted, upper, lower, group)

pred.2 = rbind(pred.hh.2, pred.hl.2, pred.lh.2, pred.ll.2)
pred.2 = pred.2 %>% mutate(group = c('High CIVIX, High Anti-immi.', 'High CIVIX, Low Anti-immi.','Low CIVIX, High Anti-immi.','Low CIVIX, Low Anti-immi.'))
pred.2 = pred.2 %>% mutate(group = factor(group, levels = c('High CIVIX, High Anti-immi.','Low CIVIX, High Anti-immi.', 'High CIVIX, Low Anti-immi.','Low CIVIX, Low Anti-immi.')))


ggplot(data = pred.2) +
  geom_errorbarh(aes(y = group, xmax = upper, xmin = lower)) + 
  geom_point(aes(y = group, x = .fitted)) +
  xlim(-1,1)+ 
  xlab("Predicted Value of General Trust (gap w/natives)") +
  ylab("") +
  geom_vline(xintercept = 0, linetype = 3)
  
ggsave("pred.ppltrst.2.jpeg")  

```


## Income level

```{r}
summary(ess_tenyr$hinctnt)
summary(ess_tenyr$hinctnt.gap)
```

```{r hinctnt, echo=FALSE}
hinctnt.1 = lm(hinctnt ~ agea + ethnic + female + edu + eubirth + citizen + civix.d*anti1, data = ess_tenyr) # absolute level
summary(hinctnt.1)
hinctnt.2 = lm(hinctnt.gap ~ agea + ethnic + female + edu + eubirth + citizen + civix.d*anti1 , data = ess_tenyr) # gap w/natives
summary(hinctnt.2)
```

```{r hinctnt.1, message=FALSE, warning=FALSE, results='asis', echo=FALSE, fig.height=3.5}

interplot(hinctnt.1, var1 = "civix.d", var2 = "anti1") + 
  xlab("Anti-immigrant Sentiments") + 
  ylab("Effect of CIVIX on Incorporation") + 
  xlim(1.8, 2.6) +
  geom_hline(yintercept = 0, linetype = 3)

ggsave("hinctnt1.jpeg")
```

```{r hinctnt.2, message=FALSE, warning=FALSE, results='asis', echo=FALSE, fig.height=3.5}

interplot(hinctnt.2, var1 = "civix.d", var2 = "anti1") + 
  xlab("Anti-immigrant Sentiments") + 
  ylab("Effect of CIVIX on Incorporation") + 
  ylim(-1.5,1.5) + xlim(1.8, 2.6) +
  geom_hline(yintercept = 0, linetype = 3)

ggsave("hinctnt2.jpeg")
```

## Subjective Financial Status

```{r}
summary(ess_tenyr$hincfel)
summary(ess_tenyr$hincfel.gap)
```

```{r hincfel, echo=FALSE}
hincfel.1 = lm(hincfel ~ agea + ethnic + female + edu + eubirth + citizen + civix.d*anti1, data = ess_tenyr) # absolute level
summary(hincfel.1)
hincfel.2 = lm(hincfel.gap ~ agea + ethnic + female + edu + eubirth + citizen + civix.d*anti1 , data = ess_tenyr) # gap w/natives
summary(hincfel.2)
```

```{r hincfel.1, message=FALSE, warning=FALSE, results='asis', echo=FALSE, fig.height=3.5}

interplot(hincfel.1, var1 = "civix.d", var2 = "anti1") + 
  xlab("Anti-immigrant Sentiments") + 
  ylab("Effect of CIVIX on Incorporation") + 
  ylim(-1.5,1.5) + xlim(1.8, 2.6) +
  geom_hline(yintercept = 0, linetype = 3)

ggsave("hincfel1.jpeg")
```

```{r hincfel.2, message=FALSE, warning=FALSE, results='asis', echo=FALSE, fig.height=3.5}

interplot(hincfel.2, var1 = "civix.d", var2 = "anti1") + 
  xlab("Anti-immigrant Sentiments") + 
  ylab("Effect of CIVIX on Incorporation") + 
  ylim(-1.5,1.5) + xlim(1.8, 2.6) +
  geom_hline(yintercept = 0, linetype = 3)

ggsave("hincfel2.jpeg")
```

```{r, echo=FALSE, fig.height=3, fig.width=6}
pred.hh.1 = hincfel.1 %>%
  broom::augment(newdata = dat.hh, predict = "response") %>%
  mutate(upper = .fitted + 1.96 * .se.fit,
         lower = .fitted - 1.96 * .se.fit,
         group = "hh") %>% 
  dplyr::select(.fitted, upper, lower, group)

pred.hl.1 = hincfel.1 %>%
  broom::augment(newdata = dat.hl, predict = "response") %>%
  mutate(upper = .fitted + 1.96 * .se.fit,
         lower = .fitted - 1.96 * .se.fit,
         group = "hl") %>% 
  dplyr::select(.fitted, upper, lower, group)

pred.lh.1 = hincfel.1 %>%
  broom::augment(newdata = dat.lh, predict = "response") %>%
  mutate(upper = .fitted + 1.96 * .se.fit,
         lower = .fitted - 1.96 * .se.fit,
         group = "lh") %>% 
  dplyr::select(.fitted, upper, lower, group)

pred.ll.1 = hincfel.1 %>%
  broom::augment(newdata = dat.ll, predict = "response") %>%
  mutate(upper = .fitted + 1.96 * .se.fit,
         lower = .fitted - 1.96 * .se.fit,
         group = "ll")%>% 
  dplyr::select(.fitted, upper, lower, group)

pred.1 = rbind(pred.hh.1, pred.hl.1, pred.lh.1, pred.ll.1)
pred.1 = pred.1 %>% mutate(group = c('High CIVIX, High Anti-immi.', 'High CIVIX, Low Anti-immi.','Low CIVIX, High Anti-immi.','Low CIVIX, Low Anti-immi.'))
pred.1 = pred.1 %>% mutate(group = factor(group, levels = c('High CIVIX, High Anti-immi.','Low CIVIX, High Anti-immi.', 'High CIVIX, Low Anti-immi.','Low CIVIX, Low Anti-immi.')))


ggplot(data = pred.1) +
  geom_errorbarh(aes(y = group, xmax = upper, xmin = lower)) + 
  geom_point(aes(y = group, x = .fitted)) +
  xlim(1.5,2.5)+ 
  xlab("Predicted Value of Subjective Financial Status") +
  ylab("")
  
ggsave("pred.hincfel.1.jpeg")  

```

```{r, echo=FALSE, fig.height=3, fig.width=6}
pred.hh.2 = hincfel.2 %>%
  broom::augment(newdata = dat.hh, predict = "response") %>%
  mutate(upper = .fitted + 1.96 * .se.fit,
         lower = .fitted - 1.96 * .se.fit,
         group = "hh") %>% 
  dplyr::select(.fitted, upper, lower, group)

pred.hl.2 = hincfel.2 %>%
  broom::augment(newdata = dat.hl, predict = "response") %>%
  mutate(upper = .fitted + 1.96 * .se.fit,
         lower = .fitted - 1.96 * .se.fit,
         group = "hl") %>% 
  dplyr::select(.fitted, upper, lower, group)

pred.lh.2 = hincfel.2 %>%
  broom::augment(newdata = dat.lh, predict = "response") %>%
  mutate(upper = .fitted + 1.96 * .se.fit,
         lower = .fitted - 1.96 * .se.fit,
         group = "lh") %>% 
  dplyr::select(.fitted, upper, lower, group)

pred.ll.2 = hincfel.2 %>%
  broom::augment(newdata = dat.ll, predict = "response") %>%
  mutate(upper = .fitted + 1.96 * .se.fit,
         lower = .fitted - 1.96 * .se.fit,
         group = "ll")%>% 
  dplyr::select(.fitted, upper, lower, group)

pred.2 = rbind(pred.hh.2, pred.hl.2, pred.lh.2, pred.ll.2)
pred.2 = pred.2 %>% mutate(group = c('High CIVIX, High Anti-immi.', 'High CIVIX, Low Anti-immi.','Low CIVIX, High Anti-immi.','Low CIVIX, Low Anti-immi.'))
pred.2 = pred.2 %>% mutate(group = factor(group, levels = c('High CIVIX, High Anti-immi.','Low CIVIX, High Anti-immi.', 'High CIVIX, Low Anti-immi.','Low CIVIX, Low Anti-immi.')))


ggplot(data = pred.2) +
  geom_errorbarh(aes(y = group, xmax = upper, xmin = lower)) + 
  geom_point(aes(y = group, x = .fitted)) +
  xlim(0,0.5)+ 
  xlab("Predicted Value of Subjective Financial Status (gap w/natives") +
  ylab("")
  
ggsave("pred.hincfel.2.jpeg")  

```
